### ISSUE TITLE
[Windows10] Command npm run watch throws error

### ISSUE THREAD

**Issue by netraagal** [squidfunk/mkdocs-material#1105]
## Description

I want to add some sources to the project via webpack. In install the environment according to doc and run ``npm run watch``. The command return an error (see bellow).

The ``make`` command seems to be the source of the problem as it doesn't exist in Windows.

## Resolution

Installation of the make command ([link](https://stackoverflow.com/a/54086635))

> GNU make is available on chocolatey.
> 
> Install chocolatey from [here](https://chocolatey.org/install).
> 
> Then, ``choco install make``

### Expected behavior

Building of the material theme.

### Actual behavior

Error in command: 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\fanie\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@6.9.0
3 info using node@v8.12.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle mkdocs-material@4.3.0~prewatch: mkdocs-material@4.3.0
6 info lifecycle mkdocs-material@4.3.0~watch: mkdocs-material@4.3.0
7 verbose lifecycle mkdocs-material@4.3.0~watch: unsafe-perm in lifecycle true
8 verbose lifecycle mkdocs-material@4.3.0~watch: PATH: C:\Users\fanie\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\fanie\Documents\Projects\mkdocs-material\node_modules\.bin;C:\Users\fanie\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\fanie\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\fanie\AppData\Local\Microsoft\WindowsApps;C:\xampp\apache\bin;C:\Users\fanie\AppData\Roaming\Composer\vendor\bin;C:\Users\fanie\AppData\Roaming\npm;C:\php;C:\Users\fanie\AppData\Local\Programs\Python\Python37-32;C:\Users\fanie\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Users\fanie\AppData\Local\GitHubDesktop\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle mkdocs-material@4.3.0~watch: CWD: C:\Users\fanie\Documents\Projects\mkdocs-material
10 silly lifecycle mkdocs-material@4.3.0~watch: Args: [ '/d /s /c', 'make -j watch' ]
11 silly lifecycle mkdocs-material@4.3.0~watch: Returned: code: 1  signal: null
12 info lifecycle mkdocs-material@4.3.0~watch: Failed to exec watch script
13 verbose stack Error: mkdocs-material@4.3.0 watch: `make -j watch`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\fanie\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\fanie\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid mkdocs-material@4.3.0
15 verbose cwd C:\Users\fanie\Documents\Projects\mkdocs-material
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fanie\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
18 verbose node v8.12.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error mkdocs-material@4.3.0 watch: `make -j watch`
22 error Exit status 1
23 error Failed at the mkdocs-material@4.3.0 watch script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

### Steps to reproduce the bug

1. Be on Windows
2. Have an environment like described [here](https://squidfunk.github.io/mkdocs-material/customization/#environment-setup)
3. Open a command window an run ``npm run watch`` command

### Package versions

* Python: `3.7.2`
* MkDocs: `1.0.4`
* Material: `4.2.0`

### System information

* OS: Windows 10

**Comment by netraagal** [comment]
Answer is on question, but I re-copy it here. For next Windows users

## Resolution

Installation of the make command ([link](https://stackoverflow.com/a/54086635))

> GNU make is available on chocolatey.
> 
> Install chocolatey from [here](https://chocolatey.org/install).
> 
> Then, ``choco install make``
