### ISSUE TITLE
Search blowing up with errors using docker

### ISSUE THREAD

**Issue by JM-Mendez** [squidfunk/mkdocs-material#1172]
## Description
Search is not working for me while using the docker image. Just clicking on the input blows up my console.

### Expected behavior
Search to work

### Actual behavior
I get this stack trace

```
[E 190715 01:29:45 web:1788] Uncaught exception GET /search/search_index.json (172.17.0.1)
    HTTPServerRequest(protocol='http', host='0.0.0.0:8000', method='GET', uri='/search/search_index.json', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado-6.0.2-py3.6-linux-x86_64.egg/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/site-packages/tornado-6.0.2-py3.6-linux-x86_64.egg/tornado/web.py", line 2649, in get
        await self.flush()
      File "/usr/local/lib/python3.6/site-packages/tornado-6.0.2-py3.6-linux-x86_64.egg/tornado/web.py", line 1097, in flush
        return self.request.connection.write(chunk)
      File "/usr/local/lib/python3.6/site-packages/tornado-6.0.2-py3.6-linux-x86_64.egg/tornado/http1connection.py", line 497, in write
        self._pending_write = self.stream.write(self._format_chunk(chunk))
      File "/usr/local/lib/python3.6/site-packages/tornado-6.0.2-py3.6-linux-x86_64.egg/tornado/http1connection.py", line 474, in _format_chunk
        "Tried to write more data than Content-Length"
    tornado.httputil.HTTPOutputError: Tried to write more data than Content-Length
```

### Steps to reproduce the bug

1. launch using docker image
2. click on the search bar

### Package versions
Whatever versions are on the latest docker build (I'm guessing 4.4.0 at this time)

### Project configuration

``` yaml
theme:
  name: 'material'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - meta
  - footnotes
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: solarized-dark
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - toc:
      permalink: true
```

### System information

* OS: macOs 10.14.5
* Browser: chrome and firefox

**Comment by squidfunk** [comment]
Please specify the command with which you are launching the Docker image.

**Comment by JM-Mendez** [comment]
I run this command from my package.json to launch the image 

```
cd ./node_modules/draftjs-fork/lib && docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
```
And the directory structure for mkdocs is
`./node_modules/draftjs-fork/lib/docs`
`./node_modules/draftjs-fork/lib/mkdocs.yml`

I should note that so far everything else appears to work fine. It's only the search that's acting up.

**Comment by squidfunk** [comment]
I tried to reproduce your problem, but everything works fine with the latest Docker image:

```
squidfunk@squidfunk:~/Desktop/mkdocs-test > mkdocs new .
INFO    -  Writing config file: ./mkdocs.yml 
INFO    -  Writing initial docs: ./docs/index.md 
squidfunk@squidfunk:~/Desktop/mkdocs-test > docker pull squidfunk/mkdocs-material
Using default tag: latest
latest: Pulling from squidfunk/mkdocs-material
e7c96db7181b: Pull complete 
799a5534f213: Pull complete 
4203dcf2ab0c: Pull complete 
e9524ee50040: Pull complete 
7cfa6613f80e: Pull complete 
0fdcb6096301: Pull complete 
2ce6ae5da8bc: Pull complete 
da3c4695d3d4: Pull complete 
02c8ffeb490a: Pull complete 
c8128c4bd900: Pull complete 
77c0256f96e9: Pull complete 
3dd7e25a06d4: Pull complete 
0ee598c8995c: Pull complete 
Digest: sha256:de394f6fafa405bdb21b44b37bc96010bcf4cb83036962060867ddc6100a53c8
Status: Downloaded newer image for squidfunk/mkdocs-material:latest
squidfunk@squidfunk:~/Desktop/mkdocs-test > docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material                          
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
[I 190715 18:16:36 server:296] Serving on http://0.0.0.0:8000
[I 190715 18:16:36 handlers:62] Start watching changes
[I 190715 18:16:36 handlers:64] Start detecting changes
[I 190715 18:16:39 handlers:135] Browser Connected: http://localhost:8000/
[I 190715 18:16:47 watcher:104] Running task: builder (delay: None)
INFO    -  Building documentation... 
[I 190715 18:16:47 handlers:95] Reload 1 waiters: /docs/mkdocs.yml
[W 190715 18:16:47 web:2246] 404 GET /search/main.js (172.17.0.1) 8.97ms
[W 190715 18:16:48 web:2246] 404 GET /search/main.js (172.17.0.1) 3.16ms
[I 190715 18:16:48 handlers:135] Browser Connected: http://localhost:8000/
```

<img width="1552" alt="Bildschirmfoto 2019-07-15 um 20 15 14" src="https://user-images.githubusercontent.com/932156/61238676-6de3cc80-a73d-11e9-930c-3137e9b383b5.png">

**Comment by JM-Mendez** [comment]
Ok, I found the issue. I'm changing into a different directory before running the docker command. If I run the command from my root directory or directly in a terminal, everything works fine. It has to do with passing `${PWD}` to the docker command when running it from a `package.json` script, since an absolute path works as well.

I haven't figured out how to fix it yet, but I think you can close this issue and I'll come back and update it with a solution when I figure it out, in case someone else wants to use a nested directory.

Thanks for your quick replies and this awesome project.

**Comment by JM-Mendez** [comment]
Ok, so I tracked down the issue. I had an inline code block that needed to be escaped. It now works properly from everywhere.

I had
```html
`<head></head>`
```

when I needed this
```html
`<head><\/head>`
```

Not sure why, and I couldn't find anything in the docs for this repo or `mkdocs`
