### ISSUE TITLE
superfences not working anymore

### ISSUE THREAD

**Issue by CesMak** [squidfunk/mkdocs-material#1456]
Hey there,

I have problems to get superfences to work for
- Ubuntu 18.04 (LTS)
- mkdocs --version --> mkdocs, version 0.16.3
- Python 3.6.9
- python -m mkdocs serve --> simact_docs/simact_env/bin/python: No module named mkdocs (I saw this command in other issues)

mkdocs.yml
```
# Extensions
markdown_extensions:
  - pymdownx.superfences:
    custom_fences:
      - name: flow
        class: uml-flowchart
        format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.arithmatex  # required for inline equations
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta # required for individual comment sites
```
Error with superfences used as in above .yml:

```
 mkdocs serve
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 521, in find_python_name
    __import__(module_name)
ModuleNotFoundError: No module named 'pymdownx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 11, in <module>
    load_entry_point('mkdocs==0.16.3', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/usr/lib/python3/dist-packages/mkdocs/commands/serve.py", line 110, in serve
    config = builder()
  File "/usr/lib/python3/dist-packages/mkdocs/commands/serve.py", line 101, in builder
    theme_dir=theme_dir
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 177, in load_config
    cfg.load_file(config_file)
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 123, in load_file
    return self.load_dict(utils.yaml_load(config_file))
  File "/usr/lib/python3/dist-packages/mkdocs/utils/__init__.py", line 71, in yaml_load
    return yaml.load(source, Loader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 537, in construct_python_name
    return self.find_python_name(suffix, node.start_mark)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 524, in find_python_name
    "cannot find module %r (%s)" % (module_name, exc), mark)
yaml.constructor.ConstructorError: while constructing a Python object
cannot find module 'pymdownx.superfences' (No module named 'pymdownx')
  in "/home/markus/Documents/simact_docs/mkdocs.yml", line 48, column 17

```

Error Without superfences used in above yml:
```
mkdocs serve
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 11, in <module>
    load_entry_point('mkdocs==0.16.3', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/usr/lib/python3/dist-packages/mkdocs/commands/serve.py", line 110, in serve
    config = builder()
  File "/usr/lib/python3/dist-packages/mkdocs/commands/serve.py", line 101, in builder
    theme_dir=theme_dir
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 181, in load_config
    errors, warnings = cfg.validate()
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 97, in validate
    run_failed, run_warnings = self._validate()
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 52, in _validate
    self[key] = config_option.validate(value)
  File "/usr/lib/python3/dist-packages/mkdocs/config/config_options.py", line 96, in validate
    return self.run_validation(value)
  File "/usr/lib/python3/dist-packages/mkdocs/config/config_options.py", line 326, in run_validation
    if value in themes:
TypeError: unhashable type: 'dict'

```

**Comment by squidfunk** [comment]
mkdocs 0.x isn’t supported since Material 2.x. Please upgrade to the latest version.

**Comment by squidfunk** [comment]
Closing. If the error persists after you upgraded to the latest versions, you may re-open the issue.
