### ISSUE TITLE
docker container squidfunk/mkdocs-material fail

### ISSUE THREAD

**Issue by jhfeng** [squidfunk/mkdocs-material#1576]
I just run command  **docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material build** based on instruction. 
it fails in material/partials/logo.html which I don't have in my local.

$ docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /docs/site

/usr/local/lib/python3.8/site-packages/pymdownx/superfences.py:634: PymdownxDeprecationWarning:
The tab option in SuperFences has been deprecated in favor of the general purpose 'pymdownx.tabbed' extension.
While you can continue to use this feature for now, it will be removed in the future.
Also be mindful of the class changes, if you require old style classes, please enable the 'legacy_tab_classes' option.

  warnings.warn(MSG_TAB_DEPRECATION, PymdownxDeprecationWarning)

Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 159, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 288, in build
    _build_theme_template(template, env, files, config, nav)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 114, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 93, in _build_template
    output = template.render(context)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/material/404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.8/site-packages/material/base.html", line 108, in top-level template code
    {% block header %}
  File "/usr/local/lib/python3.8/site-packages/material/base.html", line 109, in block "header"
    {% include "partials/header.html" %}
  File "/usr/local/lib/python3.8/site-packages/material/partials/header.html", line 7, in top-level template code
    {% include "partials/logo.html" %}
  File "/usr/local/lib/python3.8/site-packages/material/partials/logo.html", line 5, in top-level template code
    <img src="{{ config.theme.logo | url }}" alt="logo">
  File "/usr/local/lib/python3.8/site-packages/mkdocs/utils/filters.py", line 14, in url_filter
    return normalize_url(value, page=context['page'], base=context['base_url'])
  File "/usr/local/lib/python3.8/site-packages/mkdocs/utils/__init__.py", line 223, in normalize_url
    path = path_to_url(path or '.')
  File "/usr/local/lib/python3.8/site-packages/mkdocs/utils/__init__.py", line 251, in path_to_url
    return '/'.join(path.split('\\'))
AttributeError: 'dict' object has no attribute 'split'

**Comment by pawamoy** [comment]
Hi @jhfeng, did you resolve your issue? If yes, how?

**Comment by pawamoy** [comment]
I think it's due to misconfiguration of the Material theme. Upgrade instructions available here: https://squidfunk.github.io/mkdocs-material/releases/5/

**Comment by squidfunk** [comment]
It's very likely related to misconfiguration. I'm sorry that we had to change the config format, but after four years of "uncontrolled" growth it was quite necessary to clean some stuff up. A major release is a great opportunity for this and the changes are not many overall.

**Comment by pawamoy** [comment]
Of course! Thank you for all your work @squidfunk (and thanks to all the contributors)!
