### ISSUE TITLE
Cannot serve mkdocs pages after 5.0 upgrade

### ISSUE THREAD

**Issue by davis91** [squidfunk/mkdocs-material#1578]
## Description
Hello,

Trying to start our mkdocs instance after the upgrade to v5.0.1 and the following stacktrace is thrown instead:

```
> Task :mkdocsServe FAILED
[python] /usr/bin/python3.6 -m mkdocs serve -s
         INFO    -  Building documentation... 
         INFO    -  Cleaning site directory 
         INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
           - auth.md 
         Traceback (most recent call last):
           File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
             "__main__", mod_spec)
           File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
             exec(code, run_globals)
           File "/usr/lib/python3.6/site-packages/mkdocs/__main__.py", line 199, in <module>
             cli()
           File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
             return self.main(*args, **kwargs)
           File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
             rv = self.invoke(ctx)
           File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
             return _process_result(sub_ctx.command.invoke(sub_ctx))
           File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
             return ctx.invoke(self.callback, **ctx.params)
           File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
             return callback(*args, **kwargs)
           File "/usr/lib/python3.6/site-packages/mkdocs/__main__.py", line 143, in serve_command
             **kwargs
           File "/usr/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 141, in serve
             config = builder()
           File "/usr/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 136, in builder
             build(config, live_server=live_server, dirty=dirty)
           File "/usr/lib/python3.6/site-packages/mkdocs/commands/build.py", line 288, in build
             _build_theme_template(template, env, files, config, nav)
           File "/usr/lib/python3.6/site-packages/mkdocs/commands/build.py", line 114, in _build_theme_template
             output = _build_template(template_name, template, files, config, nav)
           File "/usr/lib/python3.6/site-packages/mkdocs/commands/build.py", line 93, in _build_template
             output = template.render(context)
           File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
             self.environment.handle_exception()
           File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
             reraise(*rewrite_traceback_stack(source=source))
           File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
             raise value.with_traceback(tb)
           File "/usr/lib/python3.6/site-packages/material/404.html", line 4, in top-level template code
             {% extends "base.html" %}
           File "/usr/lib/python3.6/site-packages/material/base.html", line 108, in top-level template code
             {% block header %}
           File "/usr/lib/python3.6/site-packages/material/base.html", line 109, in block "header"
             {% include "partials/header.html" %}
           File "/usr/lib/python3.6/site-packages/material/partials/header.html", line 7, in top-level template code
             {% include "partials/logo.html" %}
           File "/usr/lib/python3.6/site-packages/material/partials/logo.html", line 5, in top-level template code
             <img src="{{ config.theme.logo | url }}" alt="logo">
           File "/usr/lib/python3.6/site-packages/mkdocs/utils/filters.py", line 14, in url_filter
             return normalize_url(value, page=context['page'], base=context['base_url'])
           File "/usr/lib/python3.6/site-packages/mkdocs/utils/__init__.py", line 223, in normalize_url
             path = path_to_url(path or '.')
           File "/usr/lib/python3.6/site-packages/mkdocs/utils/__init__.py", line 251, in path_to_url
             return '/'.join(path.split('\\'))
         AttributeError: 'dict' object has no attribute 'split'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mkdocsServe'.
> Python call failed: /usr/bin/python3.6 -m mkdocs serve -s
```

Downgrading to version 4.X fixes the problem.

### Package versions

* Python: `python --version`: Python 3.6.5
* MkDocs: `mkdocs --version`: 1.1
* Material: `pip show mkdocs-material | grep -E ^Version`: 5.0.1

### System information
* OS: CentOS 7

**Comment by squidfunk** [comment]
Did you follow https://squidfunk.github.io/mkdocs-material/releases/5/#how-to-upgrade?

**Comment by davis91** [comment]
Did not. Apologies. Will have to go through the documentation first. Thanks!

**Comment by squidfunk** [comment]
Closing, as this is definitely related to missing changes in `mkdocs.yml`😉
