### ISSUE TITLE
Unclear error message when theme icon path is invalid

### ISSUE THREAD

**Issue by zoni** [squidfunk/mkdocs-material#1633]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Setting `theme.icon.logo` to a non-existent path prints ".{path}" and aborts the `serve` subcommand instead of giving a clear error message.

For example, setting `theme.icon.logo` to `"material/subject"` results in:

```
>  mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory

.icons/material/subject.svg
> echo $?
1
```

### Expected behavior

A clear error message indicating `theme.icon.logo` references a non-existing path. Potentially also non-fatal behavior when this happens.

### Actual behavior

See description.

### Steps to reproduce the bug

1. `git clone git@github.com:squidfunk/mkdocs-material.git`
1. `cd mkdocs-material`
1. `virtualenv -p $(which python3) ./venv`
1. `source ./venv/bin/activate`
1. `pip install mkdocs mkdocs-material mkdocs-minify-plugin`
1. Apply this patch to `mkdocs.yml`:

```diff
diff --git a/mkdocs.yml b/mkdocs.yml
index 11e82979..b03ab9fc 100755
--- a/mkdocs.yml
+++ b/mkdocs.yml
@@ -60,7 +60,7 @@ theme:
     text: Roboto
     code: Roboto Mono
   icon:
-    logo: logo
+    logo: material/subject
   favicon: assets/favicon.png
```

1. Run `mkdocs serve`

### Package versions

* Python: 3.8.2
* MkDocs: 1.1
* Material: 5.1.1

### Project configuration

N/A, see reproduction steps.

### System information

* OS: `Linux xps-15 5.4.34-1-lts #1 SMP Tue, 21 Apr 2020 10:35:35 +0000 x86_64 GNU/Linux`
* Browser: N/A

**Comment by zoni** [comment]
It should be noted that this issue cost me a lot of pain in the migration of 4.x to 5.x because [`subject` is a valid icon](https://material.io/resources/icons/?search=subject&icon=subject&style=baseline) which was working previously.

The lack of a clear error message meant it took quite a while to track down why mkdocs refused to run after following the migration guide.

It may also be interesting to note that if `mkdocs serve` is run with a valid path and then has its config changed, the resulting error stacktrace is more helpful:

```
[I 200422 17:25:58 server:296] Serving on http://127.0.0.1:8000
INFO    -  Serving on http://127.0.0.1:8000
[I 200422 17:25:58 handlers:62] Start watching changes
INFO    -  Start watching changes
[I 200422 17:25:58 handlers:64] Start detecting changes
INFO    -  Start detecting changes
[I 200422 17:26:03 watcher:103] Running task: builder (delay: None)
INFO    -  Running task: builder (delay: None)
INFO    -  Building documentation...
[E 200422 17:26:04 ioloop:909] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/livereload/handlers.py", line 69, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/livereload/watcher.py", line 105, in examine
        func()
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 136, in builder
        build(config, live_server=live_server, dirty=dirty)
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 288, in build
        _build_theme_template(template, env, files, config, nav)
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 114, in _build_theme_template
        output = _build_template(template_name, template, files, config, nav)
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 93, in _build_template
        output = template.render(context)
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/tmp/mkdocs-material/material/404.html", line 4, in top-level template code
        {% extends "base.html" %}
      File "/tmp/mkdocs-material/material/base.html", line 108, in top-level template code
        {% block header %}
      File "/tmp/mkdocs-material/material/base.html", line 109, in block "header"
        {% include "partials/header.html" %}
      File "/tmp/mkdocs-material/material/partials/header.html", line 7, in top-level template code
        {% include "partials/logo.html" %}
      File "/tmp/mkdocs-material/material/partials/logo.html", line 8, in top-level template code
        {% include ".icons/" ~ icon ~ ".svg" %}
      File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 197, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: .icons/material/subject.svg
ERROR   -  Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
Traceback (most recent call last):
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/tornado/ioloop.py", line 907, in _run
    return self.callback()
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/livereload/handlers.py", line 69, in poll_tasks
    filepath, delay = cls.watcher.examine()
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/livereload/watcher.py", line 105, in examine
    func()
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 288, in build
    _build_theme_template(template, env, files, config, nav)
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 114, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 93, in _build_template
    output = template.render(context)
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/tmp/mkdocs-material/material/404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/tmp/mkdocs-material/material/base.html", line 108, in top-level template code
    {% block header %}
  File "/tmp/mkdocs-material/material/base.html", line 109, in block "header"
    {% include "partials/header.html" %}
  File "/tmp/mkdocs-material/material/partials/header.html", line 7, in top-level template code
    {% include "partials/logo.html" %}
  File "/tmp/mkdocs-material/material/partials/logo.html", line 8, in top-level template code
    {% include ".icons/" ~ icon ~ ".svg" %}
  File "/tmp/mkdocs-material/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .icons/material/subject.svg
```

**Comment by squidfunk** [comment]
Unfortunately, we cannot issue error messages from the Jinja template, so it's nothing that can be fixed as part of this project. If you can isolate the error to MkDocs, you can report this issue upstream.

**Comment by squidfunk** [comment]
Closing as upstream issue.

**Comment by Reshiram110** [comment]
I seem to be getting this error even though my `mkdocs.yml` file does not specify *any* icon. Not exactly sure what's going on here, `mkdocs` and `mkdocs-material` both worked until I recently updated (via `pip uninstall` and `pip install`).

```yml
# Theme
theme:
  name: 'material'
  language : 'en'
  palette:
    primary: 'Black'
    accent: 'Orange'
  features:
    - tabs
```
```
> mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: C:\Users\Binar\Documents\Dev\<Redacted>\Repository\site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - Test.md
c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\pymdownx\superfences.py:662: PymdownxDeprecationWarning:
The tab option in SuperFences has been deprecated in favor of the general purpose 'pymdownx.tabbed' extension.
While you can continue to use this feature for now, it will be removed in the future.
Also be mindful of the class changes, if you require old style classes, please enable the 'legacy_tab_classes' option.

  warnings.warn(MSG_TAB_DEPRECATION, PymdownxDeprecationWarning)
Traceback (most recent call last):
  File "c:\users\binar\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Binar\AppData\Local\Programs\Python\Python37\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\__main__.py", line 159, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\build.py", line 288, in build
    _build_theme_template(template, env, files, config, nav)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\build.py", line 114, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\build.py", line 93, in _build_template
    output = template.render(context)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\material\404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\material\404.html", line 14, in root
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\material\base.html", line 116, in root
    {% endblock %}
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\material\base.html", line 425, in block_footer
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\material\partials\footer.html", line 58, in root
    </footer>
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\material\partials\social.html", line 33, in root
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\binar\appdata\local\programs\python\python37\lib\site-packages\jinja2\loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .icons/.svg
```
