### ISSUE TITLE
Octicons got missing

### ISSUE THREAD

**Issue by Anton-Latukha** [squidfunk/mkdocs-material#1775]
### _There are wrapper spoilers for info in report_

- [x] ... the documentation does not mention anything about my problem
- [ ] ... the problem doesn't occur with the default MkDocs template
- [ ] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

From the get-go, during debugging in Gitter `martinbira` helped to notice that Octicons support got missing on the project front page: https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#icons, observe there is literal `:octicons-octoface:` there.

Original bug report message:

I am having a trivial problem. I migrate from v4 to v5.

```yaml
extra:
  social:
    - icon: octicons/mark-github
      link: 'https://github.com/Anton-Latukha'
```

Docs, not directly, tell that Octicons seems to be supported out of the box, and that they live in the `octicons` namespace.

I exhausted variants, `octicons` or `octicon` or without namespace, `mark-github` or `github`.

As only `fontawesome` example covered in a docs, and indeed `fontawesome/brands/github-alt` works, but ` octicons/mark-github` does not worked for me.

<details><summary>Wrapper: Error log:</summary>
<p>

```text
> docker run --rm -it -p 8000:8000 -v (pwd):/docs mkdocs-material build

INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /docs/Anton-Latukha.github.io 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 285, in build
    _build_theme_template(template, env, files, config, nav)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 108, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 87, in _build_template
    output = template.render(context)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/material/404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.8/site-packages/material/base.html", line 180, in top-level template code
    {% block footer %}
  File "/usr/local/lib/python3.8/site-packages/material/base.html", line 181, in block "footer"
    {% include "partials/footer.html" %}
  File "/usr/local/lib/python3.8/site-packages/material/partials/footer.html", line 55, in top-level template code
    {% include "partials/social.html" %}
  File "/usr/local/lib/python3.8/site-packages/material/partials/social.html", line 13, in top-level template code
    {% include ".icons/" ~ social.icon ~ ".svg" %}
  File "/usr/local/lib/python3.8/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .icons/octicons/mark-github.svg
```

</details>

---

### Expected behavior

`octicons/mark-github` to work and be provided as an example in the doc.

### Actual behavior

Octicons are currently missing.

### Steps to reproduce the bug

To reproduce:

I am using the freshest `master`
1 "Prepare 5.3.3 release" commit 09e5e38a5ccd7cfaf07a58d81a95e3667d1d2d72.
2. On that checkout I use fresh current container build from the current Dockerfile.
3. So I receive `master` and rebase onto it a minor `Dockerfile` addition:
```Dockerfile
RUN  pip install --no-cache-dir \
                 pygments \
                 pymdown-extensions \
                 mkdocs-htmlproofer-plugin
```

, which should not involve in the case of the report.

### Package versions

Gathered from whithin Dockerfile container:
* `Python 3.8.1`
* `mkdocs, version 1.1.2 from /usr/local/lib/python3.8/site-packages/mkdocs (Python 3.8)`
* Material: `Version: 5.3.3`

### Project configuration

Currently:

<details><summary>Wrapper: `mkdocs.yml`:</summary>
<p>

``` yaml
# Project information
site_name: 'Latukha: Good day my friend!'
site_description: 'Official page of Anton Latukha'
site_author: 'Anton Latukha'
site_url: 'https://blog.latukha.com'
site_dir: 'Anton-Latukha.github.io'

# Structure
nav:
  - 'Home': 'index.md'
  - 'Biography': 'bio.md'
  - 'About': 'about.md'
  - Articles:
    - 'Fundamental Haskell notes': 'haskell-notes.html'
    - 'Integrating NixOS/Nix, Haskell IDE Engine, Emacs': 'NixOS-HIE-Emacs.md'
    - 'Restore of deleted LVM (Advanced)': '2017-05-04-Restore-of-deleted-LVM-(Advanced).md'
    - 'How to setup proxy to listen Spotify': '2017-04-14-How-to-setup-proxy-to-listen-Spotify.md'
    - 'SaltStack formulas': '2017-04-12-SaltStack-Formulas-install.md'

# Copyright
copyright: '2016-2019 Anton Latukha, Creative Commons ShareAlike'


# Documentation and theme
theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  font:
    text: 'Ubuntu'
    code: 'Hack'
  icon:
    logo: 'assets/images/favicon-min.png'
  logo: 'assets/images/favicon-min.png'
  favicon: 'assets/images/favicon-min.png'
  features:
    - tabs
    - instant

# Repository
repo_name: 'Profile'
repo_url: 'https://github.com/Anton-Latukha'
edit_uri: '/mkdocs-blog/tree/master/docs'
remote_name: 'u'
remote_branch: 'master'
# repo_name: 'Site content on GitHub'
# repo_url: 'https://github.com/Anton-Latukha/Anton-Latukha.github.io'

# Options
extra:
  social:
    - icon: octicons/mark-github
      link: 'https://github.com/Anton-Latukha'
    - icon: 'fontawesome/brands/gitlab'
      link: 'https://gitlab.com/Anton.Latukha'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/piroxiline'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://linkedin.com/in/anton-latukha-2a286690'
    - icon: 'octicons/heart'
      link: 'https://github.com/Anton-Latukha/Anton-Latukha.github.io/raw/master/assets/docs/AntonLatukhaCV.pdf'
    - icon: 'octicon/download'
      link: 'https://github.com/Anton-Latukha/Anton-Latukha.github.io/raw/master/assets/docs/AntonLatukhaCV.pdf'
    - icon: 'fontawesome/brands/linux'
      link: 'https://wiki.archlinux.org/index.php/Special:Contributions/Anton_Latukha'
    - icon: 'fontawesome/brands/linux'
      link: 'https://wiki.archlinux.org/index.php/Special:Contributions/PiroXiline'
  disqus: 'blog-latukha-com'

# Extensions
markdown_extensions:
  - admonition    # summaries, notes, hints or warnings.
  - codehilite:    # Table of Contents extension
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex    # Parse LaTeX formulas
  - pymdownx.betterem    # improves the handling of emphasis markup
  - pymdownx.superfences    # ability to nest code blocks under blockquotes, lists and other block elements
  - pymdownx.inlinehilite    # support for inline code highlighting
  - pymdownx.smartsymbols    # converts markup for special characters into their corresponding symbols

plugins:
  - search
  - minify
  - htmlproofer
```

</details>

---

### System information

* OS: Latest Mkdocs-material Docker Python Alpine.

**Comment by Anton-Latukha** [comment]
Without `octicons` icons use the build of configuration passes "fine".

**Comment by squidfunk** [comment]
See #1764 for reference and try `:octicon-octoface-16:`.

For reference:
https://github.com/squidfunk/mkdocs-material/tree/master/material/.icons/octicons

**Comment by squidfunk** [comment]
Documentation fixed in e2d8a0e3.

**Comment by Anton-Latukha** [comment]
Thank you.

**Comment by Anton-Latukha** [comment]
But how one can distinguish between 16px and 24px in SVG...

**Comment by Anton-Latukha** [comment]
Oh, I see, it is a "style" difference.
