### ISSUE TITLE
Octicons names have changed to include the size. Serve/build is failing

### ISSUE THREAD

**Issue by hellt** [squidfunk/mkdocs-material#1857]
- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

The icons (octicons for example) names have changed from a simple `name.svg` to `name-size.svg`.
The build/serve is now broken (starting from 5.3.0) since the name in the config does not match anymore.
The error for the `serve` command though does not point to the root cause of it:

```
❯ docker run --rm -it -p 8000:8000 -v $(pwd):/docs --entrypoint ash squidfunk/mkdocs-material:5.5.0
/docs # mkdocs serve
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 

.icons/octicons/pulse.svg
```

The build error is more precise, but still it is a trace, not a graceful error handling:
```
/docs # mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /docs/site 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 285, in build
    _build_theme_template(template, env, files, config, nav)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 108, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 87, in _build_template
    output = template.render(context)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/material/404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.8/site-packages/material/base.html", line 112, in top-level template code
    {% block header %}
  File "/usr/local/lib/python3.8/site-packages/material/base.html", line 113, in block "header"
    {% include "partials/header.html" %}
  File "/usr/local/lib/python3.8/site-packages/material/partials/header.html", line 7, in top-level template code
    {% include "partials/logo.html" %}
  File "/usr/local/lib/python3.8/site-packages/material/partials/logo.html", line 8, in top-level template code
    {% include ".icons/" ~ icon ~ ".svg" %}
  File "/usr/local/lib/python3.8/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .icons/octicons/pulse.svg
```

I'll leave it to the author to see if that needs to be handled more gracefully - [better error name?, auto-picking the icon with the lowest size instead of expecting a a full match?]

**Comment by squidfunk** [comment]
I agree. Unfortunately, we cannot do anything about it, as this project only provides a template and not the whole MkDocs runtime.
