### ISSUE TITLE
docs: no correct option

### ISSUE THREAD

**Issue by pavo976** [squidfunk/mkdocs-material#1899]
https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure

This is work fine:
```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
```

Build docker:
`Dockerfile`
```
FROM squidfunk/mkdocs-material:latest AS build
```
says:
```
ERROR   -  Config value: 'theme'. Error: The path set in theme.custom_dir ('/overrides') does not exist. 
Aborted with 1 Configuration Errors!
```

If change `custom_dir: overrides` to `theme_dir: 'overrides'` - it's ok.

this actual not for latest version:
* Python: Python 3.8.1
* MkDocs: mkdocs, version 1.1.2 from /usr/local/lib/python3.8/site-packages/mkdocs (Python 3.8)
* Material: Version: 5.5.0

**Comment by pavo976** [comment]
Or I am mistaken and I need to write not to the "material", but to the engine repository

**Comment by squidfunk** [comment]
Place use the issue template and provide more information, so we can help you. Did you create a directory for overrides? If so, where?

**Comment by pavo976** [comment]
## Description

The option described in the documentation does not correspond to reality.
[setup-and-theme-structure](https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure)

### Expected behavior

For example: edit, or remove footer page

### Actual behavior

Can't open mkdocs in web browser

### Steps to reproduce the bug

```
mkdir -p ./mkdocs-test2/{docs,overrides/partials}
```

```
cat << EOF > ./mkdocs-test2/mkdocs.yml
site_name: test1
theme:
  name: 'material'
  theme_dir: 'overrides'
EOF
```

```
cat << EOF > ./mkdocs-test2/docs/index.md
# test1

- test1
- test2
EOF
```

```
cat << EOF > ./mkdocs-test2/overrides/partials/footer.html
<html>
<head>
<title></title>
</head>
</body>
</html>
EOF
```

```
cat << EOF > ./mkdocs-test2/Dockerfile
FROM squidfunk/mkdocs-material:latest AS build

ADD docs /docs
ADD mkdocs.yml /mkdocs.yml
RUN ls -la /docs/
RUN mkdocs build -f "/mkdocs.yml"
EOF
```

```
cd ./mkdocs-test2
```

https://hub.docker.com/r/squidfunk/mkdocs-material
Start development server on http://localhost:8000

```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
```

I try to open mkdocs in web browser, got error: "The connection was reset"
In cli:

```
$ docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
INFO    -  Building documentation... 
WARNING -  Config value: 'dev_addr'. Warning: The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead. 
INFO    -  Cleaning site directory 
INFO    -  Documentation built in 0.23 seconds 
[I 200902 11:20:07 server:335] Serving on http://0.0.0.0:8000
INFO    -  Serving on http://0.0.0.0:8000
[I 200902 11:20:07 handlers:62] Start watching changes
INFO    -  Start watching changes
[I 200902 11:20:07 handlers:64] Start detecting changes
INFO    -  Start detecting changes
[I 200902 11:20:11 handlers:135] Browser Connected: http://127.0.0.1:8000/
INFO    -  Browser Connected: http://127.0.0.1:8000/
[I 200902 11:20:22 handlers:135] Browser Connected: http://127.0.0.1:8000/
INFO    -  Browser Connected: http://127.0.0.1:8000/
[E 200902 11:22:15 web:1788] Uncaught exception GET / (172.17.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 2653, in get
        await self.flush()
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1093, in flush
        return self.request.connection.write_headers(
      File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 462, in write_headers
        data += self._format_chunk(chunk)
      File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 473, in _format_chunk
        raise httputil.HTTPOutputError(
    tornado.httputil.HTTPOutputError: Tried to write more data than Content-Length
ERROR   -  Uncaught exception GET / (172.17.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/', version='HTTP/1.1', remote_ip='172.17.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 2653, in get
    await self.flush()
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1093, in flush
    return self.request.connection.write_headers(
  File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 462, in write_headers
    data += self._format_chunk(chunk)
  File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 473, in _format_chunk
    raise httputil.HTTPOutputError(
tornado.httputil.HTTPOutputError: Tried to write more data than Content-Length
[E 200902 11:22:15 web:1198] Cannot send error response after headers written
ERROR   -  Cannot send error response after headers written
...
```

### Package versions

```
$ docker ps|\grep mkdocs
edf511343e73        squidfunk/mkdocs-material   "mkdocs serve --dev-…"   About a minute ago   Up About a minute   0.0.0.0:8000->8000/tcp   objective_kare
```

* Python: Python 3.8.1
* MkDocs: mkdocs, version 1.1.2 from /usr/local/lib/python3.8/site-packages/mkdocs (Python 3.8)
* Material: Version: 5.5.12


### solution

Use the `theme_dir` parameter in the `mkdocs.yml` configuration file 
instead of the `custom_dir` specified in the documentation

**Comment by squidfunk** [comment]
1. We cannot provide support for when you extend the Docker image. Please use the official Docker image.
2. The variable must be named `custom_dir`, not `theme_dir`.

**Comment by danipenaperez** [comment]
Hi, is an old question,

Partials are processed at build time, so must be placed on root shared path  ${PWD} and not at  ${PWD}/docs.

If you want to use "runtime assets", these should be located at /docs/assets/(js|images|css)/ (.js, .png .css) always a child of ${PWD}/docs/**

This works for me:
```sh
.
├── docs
│   ├── index.md
│   ├── nav
│   │   ├── index.md
│   └── runtime_assets   #could be referenced as links in my markdown pages (or logo configs, etc..)
│       ├── css
│       ├── icons
│       └── javascript
├── mkdocs.yml
└── overrides  # only availabe at build time to process template overwritting 
    ├── assets
    ├── main.html
    └── partials
        ├── copyright.html
        └── header.html
```

mkdocs.yaml looks like this:

```yaml
theme:
  name: material
  custom_dir: overrides         # points to  -v ${PWD}/overrides (docker run volume)
```
  
And docker run in this way:

docker run --rm -it -p 9999:8000 -v /home/dpena/mkdocs/test:/docs squidfunk/mkdocs-material


Hope helps to anyone that gets in the same trouble.
