### ISSUE TITLE
self.slugify ...TypeError: 'str' object is not callable!

### ISSUE THREAD

**Issue by Jackiexiao** [squidfunk/mkdocs-material#1905]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

toc not produce good and readable identifiers, 

<img src="https://user-images.githubusercontent.com/18050469/92320605-3f1d6980-f055-11ea-96a4-24ee54c0c754.png" width="350">

I try to change slugs
```
markdown_extensions:
  - toc:
      slugify: pymdownx.slugs.uslugify
```

but error happen

<details>
  <summary>..self.slugify ...TypeError: 'str' object is not callable!</summary>

```
[E 200906 15:11:48 ioloop:638] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "C:\Users\Mi\Anaconda3\lib\site-packages\tornado\ioloop.py", line 1026, in _run
        return self.callback()
      File "C:\Users\Mi\Anaconda3\lib\site-packages\livereload\handlers.py", line 69, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "C:\Users\Mi\Anaconda3\lib\site-packages\livereload\watcher.py", line 119, in examine
        func()
      File "C:\Users\Mi\Anaconda3\lib\site-packages\mkdocs\commands\serve.py", line 136, in builder
        build(config, live_server=live_server, dirty=dirty)
      File "C:\Users\Mi\Anaconda3\lib\site-packages\mkdocs\commands\build.py", line 271, in build
        _populate_page(file.page, config, files, dirty)
      File "C:\Users\Mi\Anaconda3\lib\site-packages\mkdocs\commands\build.py", line 171, in _populate_page
        page.render(config, files)
      File "C:\Users\Mi\Anaconda3\lib\site-packages\mkdocs\structure\pages.py", line 175, in render
        self.content = md.convert(self.markdown)
      File "C:\Users\Mi\Anaconda3\lib\site-packages\markdown\core.py", line 267, in convert
        newRoot = treeprocessor.run(root)
      File "C:\Users\Mi\Anaconda3\lib\site-packages\markdown\extensions\toc.py", line 274, in run
        el.attrib["id"] = unique(self.slugify(innertext, self.sep), used_ids)
    TypeError: 'str' object is not callable
ERROR   -  Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
Traceback (most recent call last):
  File "C:\Users\Mi\Anaconda3\lib\site-packages\tornado\ioloop.py", line 1026, in _run
    return self.callback()
  File "C:\Users\Mi\Anaconda3\lib\site-packages\livereload\handlers.py", line 69, in poll_tasks
    filepath, delay = cls.watcher.examine()
  File "C:\Users\Mi\Anaconda3\lib\site-packages\livereload\watcher.py", line 119, in examine
    func()
  File "C:\Users\Mi\Anaconda3\lib\site-packages\mkdocs\commands\serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "C:\Users\Mi\Anaconda3\lib\site-packages\mkdocs\commands\build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "C:\Users\Mi\Anaconda3\lib\site-packages\mkdocs\commands\build.py", line 171, in _populate_page
    page.render(config, files)
  File "C:\Users\Mi\Anaconda3\lib\site-packages\mkdocs\structure\pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "C:\Users\Mi\Anaconda3\lib\site-packages\markdown\core.py", line 267, in convert
    newRoot = treeprocessor.run(root)
  File "C:\Users\Mi\Anaconda3\lib\site-packages\markdown\extensions\toc.py", line 274, in run
    el.attrib["id"] = unique(self.slugify(innertext, self.sep), used_ids)
TypeError: 'str' object is not callable
```
</details>

### Expected behavior

`[#标题](#标题)` instead of `[#标题](#_1)`

### Steps to reproduce the bug

add `slugify: pymdownx.slugs.uslugify` to `mkdocs.yml`

### Package versions

```
Python 3.6.10 :: Anaconda, Inc.
mkdocs, version 1.1.2 
mkdocs-material Version: 5.5.12
```

### Project configuration

<details>
  <summary>mkdocs.yml</summary>

```
site_name: Jackie的博客
strict: false
theme:
  name: material
  favicon: attachment/portrait.png
  language: zh 
  features:
    - navigation.expand 
    - tabs 
    - instant # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
markdown_extensions: 
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break 
  - toc:
      permalink: '#' # heading anchor 
      #      slugify: pymdownx.slugs.gfm_encoded
      slugify: pymdownx.slugs.uslugify
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
plugins:
  - search
  - roamlinks 
    #- autolinks 
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
```

</details>

### System information

* OS: window10
* Browser: chrome

**Comment by squidfunk** [comment]
Thanks for reporting! That's actually an error in the documentation, which [I just fixed](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents) in 9ec0d4d8 😊 The syntax is:

``` yaml
markdown_extensions:
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
```

Also thanks for sponsoring! ❤️

**Comment by Jackiexiao** [comment]
thx!! Also why not set default to support chinese (and other language using utf-8 encoding) (both search and title anchor)

in order to support chinese, I have to change `mkdocs.yml`
```
theme:
  name: material
  language: zh   # to solve search issue
markdown_extensions: 
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify # to solve title anchor
```

Or could you add this to document in case other people encounter same problem as me.

**Comment by squidfunk** [comment]
Unfortunately, we cannot set defaults for `markdown_extensions` from this theme – it's completely up to the user. 

Language configuration is all documented here:
- https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/
- https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-search-language
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/

We could add a note on slugs to the language guide, or what are you exactly missing from the documentation?

**Comment by Jackiexiao** [comment]
Add a note on slugs to the language guide 
---------
This one is great, thx

**Comment by squidfunk** [comment]
Added a note in b2e84232.
