### ISSUE TITLE
Exception 'page' is undefined

### ISSUE THREAD

**Issue by miraai** [squidfunk/mkdocs-material#272]
## Description

Okay, so I've been trying to build my docs with Material theme for a while now. I've tried everything, to be honest.
Also, it works perfectly fine if I run it locally, but otherwise, my build on RTD just won't pass.

### Expected behavior

What I want is to use the theme on rtd as I do locally.

### Actual behavior

When trying to build, i get this error:
```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/giveaway/checkouts/latest/_build/html 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/mkdocs/__main__.py", line 137, in build_command
    ), clean_site_dir=clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/mkdocs/commands/build.py", line 289, in build
    build_pages(config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/mkdocs/commands/build.py", line 233, in build_pages
    build_template('404.html', env, config, site_navigation)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/mkdocs/commands/build.py", line 148, in build_template
    output_content = template.render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/checkouts/latest/material/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/checkouts/latest/material/base.html", line 86, in top-level template code
    {% block header %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/checkouts/latest/material/base.html", line 87, in block "header"
    {% include "partials/header.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/checkouts/latest/material/partials/header.html", line 19, in top-level template code
    {% block site_name %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/checkouts/latest/material/partials/header.html", line 27, in block "site_name"
    {{ page.title | default(config.site_name, true) }}
  File "/home/docs/checkouts/readthedocs.org/user_builds/giveaway/envs/latest/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'page' is undefined
```

### Steps to reproduce the bug

1. Push to git
2. Clone
3. Build

### Package versions

* Python: `Python 3.6.1`
* MkDocs: `mkdocs, version 0.16.3`
* Material: `Version: 1.5.4`

### Project configuration

``` yaml
site_name: Giveaway
theme_dir: material
copyright: "Giveaway is licensed under the <a href='https://github.com/miraai/GiveawayRTD/blob/master/docs/terms.md'>MIT license."
repo_url: https://github.com/miraai/GiveawayRTD
pages:
- Home: index.md
- Licence: licence.md
- Introduction: intro.md
- General Description: general.md
- Specific Requirements: specific.md
- Database Model: database.md
```

### System information

* OS: Windows 10
* Browser: Waterfox

**Comment by squidfunk** [comment]
I have no experience in deploying on RTD but I remember some discussion that it is not possible with MkDocs. Have you searched the MkDocs issue tracker for a similar problem?

**Comment by miraai** [comment]
Yes, I did. And it doesn't say that anywhere. 
Is there something else I could use instead of RTD?

**Comment by squidfunk** [comment]
Use GitHub pages: http://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages

**Comment by miraai** [comment]
Thank you!

**Comment by squidfunk** [comment]
I've just seen that Uber uses Material on RTD and everything seems to work. Maybe you can check how they did it and report if you're successful: http://jaeger.readthedocs.io/en/latest/
