### ISSUE TITLE
Building with 7.1.8 fails (not with 7.1.7)

### ISSUE THREAD

**Issue by Guts** [squidfunk/mkdocs-material#2752]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [X] ... the problem doesn't occur with the default MkDocs template
- [X] ... the problem is not in any of my customizations (CSS, JS, template)
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

## Description

Building my website (https://github.com/geotribu/website/) with version 7.1.7 is working perfectly (and with the mkdocs default)  but not with the latest version 7.1.8.

### Expected behavior

Succeeded build.

### Steps to reproduce the bug

1. Install latest version
2. Launch the build in strict mode

```log
DEBUG   -  Building theme template: 404.html
Traceback (most recent call last):
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Documents\GitHub\Geotribu\website\.venv\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\click\core.py", line 1137, in __call__
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\mkdocs\__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\mkdocs\commands\build.py", line 285, in build
    _build_theme_template(template, env, files, config, nav)
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\mkdocs\commands\build.py", line 108, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\mkdocs\commands\build.py", line 87, in _build_template
    output = template.render(context)
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\material\404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "./content/theme/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\material\base.html", line 73, in top-level template code
    {% block analytics %}
  File "./content/theme/main.html", line 141, in block "analytics"
    {{ super() }}
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\material\base.html", line 74, in block "analytics"
    {% include "partials/integrations/analytics.html" %}
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\material\partials\integrations\analytics.html", line 11, in top-level template code
    {% include "partials/integrations/analytics/" ~ provider ~ ".html" %}
  File "c:\users\user\documents\github\geotribu\website\.venv\lib\site-packages\material\partials\integrations\analytics\google.html", line 10, in top-level template code
    {% if property.startswith("G-") %}
jinja2.exceptions.UndefinedError: 'None' has no attribute 'startswith'
```

### Package versions

* Python: `3.8`
* MkDocs: `1.1.2`
* Material: `7.18`

### Project configuration

``` yaml

# Theme
theme:
  name: 'material'
  custom_dir: './content/theme/'
  favicon: "https://cdn.geotribu.fr/img/internal/charte/geotribu_logo_64x64.png"

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - navigation.instant
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  font: false
  icon:
    repo: fontawesome/brands/github-alt
  language: 'fr'
  logo: "https://cdn.geotribu.fr/img/internal/charte/geotribu_logo_64x64.png"
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Basculer en mode clair

# Integrations with 3rd party
google_analytics:
  - !!python/object/apply:os.getenv ["MKDOCS_GOOGLE_ANALYTICS_KEY"]
  - 'auto'
```

### System information

* OS: Windows 10
* Browser: Firefox latest (but not relevant)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by jaceklaskowski** [comment]
This is due to the brand new support for [Google Analytics 4](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#google-analytics).

**Comment by squidfunk** [comment]
Does this happen on a clean installation? Maybe the Jinja version is too old.

**Comment by Guts** [comment]
> Does this happen on a clean installation? Maybe the Jinja version is too old.

Yes. First failed on CI: https://github.com/geotribu/website/runs/2810555274?check_suite_focus=true#step:8:1159

> Also please try to remove your overrides and check whether the error persists.

I will but it's still strange that it's failing only with the last patch version no?

**Comment by squidfunk** [comment]
Overrides may suddenly fail with patch version upgrades, as it's not predictable what users change in overrides. Yet, I try to keep backward compat to a maximum which is the same for this change.

**Comment by michaelmcmillan** [comment]
Same exact report here.

**Comment by squidfunk** [comment]
@michaelmcmillan couly you please provide a _reproducible example_, i.e. without overrides and minimal configuration.

**Comment by Guts** [comment]
The error occurs inheriting partial from the analytics block:

```jinja
{% block analytics %}
      {{ super() }}
{% endblock %}
```

Commenting out [this line ](https://github.com/geotribu/website/blob/master/content/theme/main.html#L141), fix the build, but do not include the partial.

**Comment by squidfunk** [comment]
Thanks for providing further information. Still, it's not reproducible to me. It can not be ruled out that this does something to do with your partials and I can't reproduce it locally. Please provide a clean, reproducible example without customizations.

**Comment by Guts** [comment]
> Thanks for providing further information. Still, it's not reproducible to me. It can not be ruled out that this has something to do with your partials and I can't reproduce it locally. Please provide a clean, reproducible example without customizations.

Fair enough. I'll try but not sure to get enough time before next week-end.

**Comment by Guts** [comment]
@squidfunk as mentioned, fixed moving the GA integration into the extra section: https://github.com/geotribu/website/pull/375

**Comment by squidfunk** [comment]
Okay, great, sorry that this wasn't clear to me. So we can consider this issue resolved, right?

**Comment by Guts** [comment]
> So we can consider this issue resolved, right?

Right.
