### ISSUE TITLE
Social cards fail to use an svg logo 

### ISSUE THREAD

**Issue by hellt** [squidfunk/mkdocs-material#3250]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

this is a continuation of https://github.com/squidfunk/mkdocs-material/discussions/3246
Social cards prevent mkdocs-material build, when a doc site uses an svg logo provided in the config as such:

```yaml
theme:
  name: material
  logo: images/srlinux.svg # this doesn't work
```

As @squidfunk mentioned, this is likely because the logo needs to be in a PNG format, but I struggle to see that in the mkdocs.yml file of the mkdocs-material doc site.

Moreover, how would one use SVG logo for site's logo and PNG for social cards? Seems like `cards_logo` config option pointing to a png file for social cards is needed to allow that.

### Expected behaviour

Social cards emit a meaningful error in the case SVGs are not supported, instead of a trace back.

### Actual behaviour

build fails with a traceback

```
docker run -it --rm -p 8001:8000 -v $(pwd):/docs ghcr.io/srl-labs/mkdocs-material-insiders:3.2.3
INFO     -  Building documentation...
WARNING  -  Config value: 'dev_addr'. Warning: The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
INFO     -  Cleaning site directory
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - alwayson.md
ERROR    -  Error reading page 'index.md': images do not match
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 177, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 54, in serve
    config = builder()
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 49, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 170, in _populate_page
    page.markdown = config['plugins'].run_event(
  File "/usr/local/lib/python3.9/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/material/plugins/social/plugin.py", line 119, in on_page_markdown
    image = self.__render_card(site_name, title, description)
  File "/usr/local/lib/python3.9/site-packages/material/plugins/social/plugin.py", line 137, in __render_card
    image.alpha_composite(
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 1633, in alpha_composite
    result = alpha_composite(background, overlay)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 3051, in alpha_composite
    return im1._new(core.alpha_composite(im1.im, im2.im))
ValueError: images do not match
make: *** [Makefile:17: isite] Error 1
```

### Steps to reproduce

1. use an svg file a theme's logo
2. enable `social` plugin
3. try to build the site

### Package versions

- mkdocs-insiders 3.2.3

### Configuration

```yaml
site_name: Learn SR Linux
nav:
  - Home: index.md

theme:
  name: material
  custom_dir: docs/overrides

  features:
    - navigation.top
    - navigation.tabs

  language: en
  font:
    text: Roboto # trying embedded font instead of a NokiaPureText
    code: Fira Mono
  logo: images/srlinux.svg # this doesn't work. Comment out to see that it works

# Plugins
plugins:
  - social

# Extensions

extra_css:
  - stylesheets/nokia.css
```
```


### System information

NA

**Comment by squidfunk** [comment]
I was able to reproduce the error when I take the logo from your site (SRLinux). Then I checked whether this happens with every SVG image, and it doesn't – for example, when I take the logo from [fastapi.tiangolo.com](https://fastapi.tiangolo.com/) and set it via `theme.logo`, it works as expected. No error, all images are generated correctly. I then installed a tool called `svgcheck` and ran it on both images.

Result for the working image:

```
Parsing file docs/icon-white.svg
docs/icon-white.svg:16: The element 'metadata' is not allowed as a child of 'svg'
docs/icon-white.svg:33: Style property 'fill' promoted to attribute
docs/icon-white.svg:33: Style property 'stroke-width' promoted to attribute
docs/icon-white.svg:37: Style property 'stroke-width' promoted to attribute
docs/icon-white.svg:37: Style property 'fill' promoted to attribute
INFO: File conforms to SVG requirements.
```

Result for your image, which breaks:

```
Parsing file docs/test.svg
docs/test.svg:1: Style property 'fill' promoted to attribute
docs/test.svg:1: The attribute 'fill' does not allow the value 'rgb(255, 255, 255)', replaced with 'white'
docs/test.svg:1: Malformed field '['']' in style attribute found. Field removed.
docs/test.svg:1: Style property 'fill' promoted to attribute
docs/test.svg:1: The attribute 'fill' does not allow the value 'rgb(0, 0, 0)', replaced with 'black'
docs/test.svg:1: Style property 'fill' promoted to attribute
docs/test.svg:1: The attribute 'fill' does not allow the value 'rgb(0, 0, 0)', replaced with 'black'
docs/test.svg:1: Malformed field '['']' in style attribute found. Field removed.
docs/test.svg:1: Style property 'fill' promoted to attribute
docs/test.svg:1: The attribute 'fill' does not allow the value 'rgb(0, 0, 0)', replaced with 'black'
docs/test.svg:1: Style property 'fill' promoted to attribute
docs/test.svg:1: The attribute 'fill' does not allow the value 'rgb(0, 0, 0)', replaced with 'black'
docs/test.svg:1: Style property 'fill' promoted to attribute
docs/test.svg:1: The attribute 'fill' does not allow the value 'rgb(0, 0, 0)', replaced with 'black'
docs/test.svg:1: Style property 'fill' promoted to attribute
docs/test.svg:1: The attribute 'fill' does not allow the value 'rgb(0, 0, 0)', replaced with 'black'
docs/test.svg:1: Style property 'fill' promoted to attribute
docs/test.svg:1: The attribute 'fill' does not allow the value 'rgb(0, 0, 0)', replaced with 'black'
ERROR: File does not conform to SVG requirements
```

Thus, it seems that PIL chokes on invalid SVG files. Therefore, please ensure that your SVG is in fact correct. If this still happens with a non malformed SVG, please reopen.
