### ISSUE TITLE
tags_file: tags.md index file causing build error

### ISSUE THREAD

**Issue by waako** [squidfunk/mkdocs-material#3628]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When trying to setup tags index page, on build it throws:  
`Error reading page 'tags.md': '<' not supported between instances of 'NoneType' and 'str'`

Same behaviour with `mkdocs` or `readthedocs` theme, but as it's a mkdocs-material plugin that seems to make sense ?
Issue still occurs even without any other plugins installed / enabled.

### Expected behaviour

Build the site with tags linked to tags index page.

### Actual behaviour

Fails on build/serve with following:

```
INFO     -  Building documentation...
WARNING  -  Config value: 'dev_addr'. Warning: The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect
            to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party
            production-ready server instead.
INFO     -  Cleaning site directory
WARNING  -  Documentation file 'coding/build-tools.md' contains a link to 'coding/theme-troubleshooting.md' which is not found in the documentation
            files.
WARNING  -  Documentation file 'under-discussion/README.md' contains a link to 'under-discussion/forms.md' which is not found in the documentation
            files.
ERROR    -  Error reading page 'tags.md': '<' not supported between instances of 'NoneType' and 'str'
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 177, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 54, in serve
    config = builder()
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 49, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 170, in _populate_page
    page.markdown = config['plugins'].run_event(
  File "/usr/local/lib/python3.9/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/material/plugins/tags/plugin.py", line 67, in on_page_markdown
    return self.__render_tag_index(markdown)
  File "/usr/local/lib/python3.9/site-packages/material/plugins/tags/plugin.py", line 91, in __render_tag_index
    for args in sorted(self.tags.items())
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

### Steps to reproduce

1. Ensure on mkdocs-material version 8.2.0 or newer
2. Enable tags in plugins
3. Set tags plugin option `tags_file: tags.md`
4. Run `mkdocs build / serve`

### Package versions

- Python: `python 3.9.2`
- MkDocs: `mkdocs 1.2.3`
- Material: `8.2.1`

### Configuration

```yaml
site_name: Knowledge

theme:
  name: 'material'
  custom_dir: theme_overrides/
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    primary: blue

repo_name: knowledge
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - meta
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - tags:
      tags_file: tags.md
```

### System information

Using Docker image `squidfunk/mkdocs-material`

**Comment by waako** [comment]
Sorry, should have thought of that 🤦 

I was using `Nick-SHM/mkdocs-tags` plugin previously, so all markdown files have metadata:  
```markdown
---
title: Page title
tags:
  - people
  - connections
  - roles
  - teams
  - names
---
```

Some pages do appear to have double indentation, so:
```markdown
---
title: Another page title
tags:
      - setup
      - another-tag
---
```
_In case that might affect it, but seems unlikely ?_

`tags.md` is in root of `docs` folder (so `docs/tags.md`), and contains content as per [docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags#adding-a-tags-index)
```markdown
# Tags

[TAGS]
```

Anything else I'm missing that can help ?  
This is an old(ish) site, and some metadata still has things like `path` and `source` from old versions for the `edit` link etc. Assume that's not a potential issue ?
Thanks!

**Comment by waako** [comment]
Thanks for looking into it, and for steps forward.

I have isolated the issue, by deleting all folders/files in `docs` and restoring one by one, and it's simply down to an empty tag!

Someone forgot to finish adding a tag, so file metadata had:   
```markdown
---
title: Page Title
path: tree/main/docs/folder
source: filename.md
tags:
  - tag1
  - tag2
  - 
---
```

Removing the "empty" tag fixed the build error!
Interesting that it didn't cause any issues previously with `mkdocs-tags` plugin.
