### ISSUE TITLE
MkDocs on Windows fails while using backslash on the blog plugin with `blog_dir: blog`

### ISSUE THREAD

**Issue by jimenezk** [squidfunk/mkdocs-material#4361]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

MkDocs fails when using a backslash (`\`) in combination with the blog plugin of mkdocs-material.

### Expected behaviour

The expected behavior is mkdocs-material theme to use the blog directory instead of the root.

### Actual behaviour

```
AzureAD+KevinJimenezMendez@DESKTOP-NPK7G0C MINGW64 ~/Read em/my-new-blog
$ mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
Traceback (most recent call last):
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs\__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs\commands\serve.py", line 63, in serve
    config = builder()
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs\commands\serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs\commands\build.py", line 282, in build
    files = config['plugins'].run_event('files', files, config=config)
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs\plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "C:\Users\KevinJimenezMendez\AppData\Local\Programs\Python\Python310\lib\site-packages\material\plugins\blog\plugin.py", line 272, in on_files
    root.append({ name: data })
AttributeError: 'NoneType' object has no attribute 'append'

AzureAD+KevinJimenezMendez@DESKTOP-NPK7G0C MINGW64 ~/Read em/my-new-blog
$

```

### Steps to reproduce

While in combination with `blog_dir: blog`, 

this fails in Windows, but PASS in Github Actions.

```
 - Blog:
   - blog/index.md
```

This works in Windows, but FAILS in Github Actions.

```
[my-new-blog.zip](https://github.com/squidfunk/mkdocs-material/files/9567652/my-new-blog.zip)

- Blog:
  - blog\index.md
```

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

$ python --version
Python 3.10.7

$ mkdocs --version
mkdocs, version 1.3.1 

$ pip show mkdocs-material | grep -E ^Version
Version: 8.5.0+insiders.4.23.3

### Configuration

```yaml
site_name: My Blog
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
plugins:
  - meta
  - blog:
      blog_dir: blog
  - search
  - tags
nav:
  - index.md
  - Blog:
    - blog/index.md
```

### System information

- Operating system: Windows 10, running Ubuntu on WSL
- Browser: Mozilla Firefox 104.0.2 (64-bit)

**Comment by squidfunk** [comment]
Thanks for reporting. Did you check the latest `master`? I fixed some path issues today, so the following syntax should work:

``` yaml
nav:
  - index.md
  - Blog:
    - blog/index.md
```
