### ISSUE TITLE
git-committers started error

### ISSUE THREAD

**Issue by qianmoQ** [squidfunk/mkdocs-material#4388]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

When the document directory is not in the project root directory, the plug-in cannot scan to the repository, and the docs directory does not contain the `.git` directory

```bash
INFO     -  git-committers plugin ENABLED
WARNING  -  no git token provided in GH_TOKEN environment variable
Traceback (most recent call last):
  File "/opt/homebrew/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/opt/homebrew/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/opt/homebrew/lib/python3.9/site-packages/mkdocs/commands/build.py", line 257, in build
    config = config['plugins'].run_event('config', config)
  File "/opt/homebrew/lib/python3.9/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/mkdocs_git_committers_plugin_2/plugin.py", line 56, in on_config
    self.localrepo = Repo(".")
  File "/opt/homebrew/lib/python3.9/site-packages/git/repo/base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/opt/homebrew/lib/python3.9/site-packages/git/repo/base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
```

### Expected behaviour

load plugin successful

### Actual behaviour

When the document directory is not in the project root directory, the plug-in cannot scan to the repository, and the docs directory does not contain the `.git` directory

### Steps to reproduce

When the document directory is not in the project root directory, the plug-in cannot scan to the repository, and the docs directory does not contain the `.git` directory

### Package versions

- Python: `3.9`
- MkDocs: `1.3.0`
- Material: `8.5.3+insiders.4.23.5`

### Configuration

```yaml
site_name: DataCap (incubator)
site_url: https://databap.incubator.edurt.io/
site_author: EdurtIO
site_description: >-
  DataCap is integrated software for data transformation, integration and visualization.
repo_name: EdurtIO/incubator-datacap
repo_url: https://github.com/EdurtIO/incubator-datacap
edit_uri: "https://github.com/EdurtIO/incubator-datacap/blob/master/docs"

copyright: Copyright &copy; 2022 EdurtIO

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/open-source-initiative
  favicon: material/open-source-initiative

  include_search_page: false
  search_index_only: true

  language: zh
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EdurtIO
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/qianmoQ/
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: EdurtIO
      repo: incubator-datacap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

use_directory_urls: false
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - git-authors
  - git-committers:
      repository: EdurtIO/incubator-datacap

nav:
  - Home: index.md
  - Reference:
      - Plugin: guide/plugin.md
```

### System information

- Operating system: Mac
- Browser: Chrome

**Comment by squidfunk** [comment]
Thanks for reporting! The `git-committer` plugin is an upstream project of ours – we are not the maintainers. Please report it to the maintainers of the plugin.
