### ISSUE TITLE
Build fails with social plugin enabled

### ISSUE THREAD

**Issue by vedranmiletic** [squidfunk/mkdocs-material#4507]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

```
ERROR    -  Error reading page 'index.md': expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/usr/lib/python3.10/site-packages/mkdocs/commands/build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/lib/python3.10/site-packages/mkdocs/commands/build.py", line 177, in _populate_page
    page.markdown = config.plugins.run_event(
  File "/usr/lib/python3.10/site-packages/mkdocs/plugins.py", line 514, in run_event
    result = method(item, **kwargs)
  File "/home/vedranm/.local/lib/python3.10/site-packages/material/plugins/social/plugin.py", line 152, in on_page_markdown
    page.meta["meta"] = meta + self._generate_meta(page, config)
  File "/home/vedranm/.local/lib/python3.10/site-packages/material/plugins/social/plugin.py", line 264, in _generate_meta
    url = "{}.png".format(posixpath.join(
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Expected behaviour

Build does not fail.

### Actual behaviour

Build fails.

### Steps to reproduce

1. `git clone https://github.com/razmjena/razmjena.git` (this is a very minimal site, but I can minimize it further if needed)
2. `cd razmjena`
3. `mkdocs build`

### Package versions

- Python: `Python 3.10.8`
- MkDocs: `mkdocs, version 1.4.0 from /usr/lib/python3.10/site-packages/mkdocs (Python 3.10)`
- Material: `Version: 8.5.6`

### Configuration

```yaml
site_name: Razmjena

theme:
  name: material
plugins:
  - search
  - social
```

### System information

- Operating system: Arch Linux
- Browser: Firefox 105

**Comment by squidfunk** [comment]
Thanks for reporting. Please provide a self-contained, minimal reproducible example and attach it here as a zip.

**Comment by squidfunk** [comment]
I looked into it, and it's a configuration error. You didn't provide a value for `site_dir`, [which is mandatory](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#built-in-social-plugin):

> First, ensure you've installed all [dependencies](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#dependencies) and have a valid [site_url](https://www.mkdocs.org/user-guide/configuration/#site_url), as social preview images must be referenced via absolute URLs.

I'm currently refactoring the social plugin, which will also raise an error when the `site_url` is not defined. Until then, the documentation mentions in the first sentence that the `site_url` must be set.

**Comment by vedranmiletic** [comment]
Oh, I see, sorry. Looking forward to the error message being less cryptic.

**Comment by squidfunk** [comment]
Added in b8161e017.

**Comment by vedranmiletic** [comment]
Thank you very much!
