### ISSUE TITLE
Enable Bread Crumb Parent linking in the style of Google Maps API Doc

### ISSUE THREAD

**Issue by martinbira** [squidfunk/mkdocs-material#459]
## Description

For the current inhouse documentation project a request came to investigate the possibility to make the bread crumbs (rendered by `{{ parent.title }}` in the header.html partial) clickable. User test confirmed that it would be a positive addition to the docs site. However, the `{{ parent.title }}` is generated from the `pages:` setup in mkdocs.yml and items in the `pages:` setup that have sub pages are not allowed to have pages of their own.

### Expected/desired behavior
When the header.html partial is modified to use `{{ parent.url }}` and a page link is added items in the `pages:` setup that have sub pages in mkdocs.yml, the rendered page should have links to the parent page in the bread crumb. See [https://developers.google.com/maps/documentation/javascript/places](https://developers.google.com/maps/documentation/javascript/places) for example.

### Actual behavior
1. If page is not set but only header.html is changed: Working links but to current page.
2. If page is set according to Steps to Reproduce: Parser error, see snippet further down.

### Steps to reproduce the bug
1. Change partial header.html to create links in the bread crumb: 
```
{% for parent in page.ancestors %}
  <span class="md-header-nav__parent">
    <a href="{{ parent.url }}" title="{{ parent.title }}">{{ parent.title }}</a>
  </span>
{% endfor %}
```
**Result:** Working links for parents but to current page in example bread crumb Guides / Integration Overview / Data Integration

2 .In the mkdocs.yml file, add urls to Guides and Integration Overview items in page structure
```
91  pages:
92  - Home: index.md
93  - Guides: guides/index.md
94   - Overview: guides/index.md
95   - Integration Overview: guides/integration-overview/index.md
96     - Introduction: guides/integration-overview/index.md
97     - Data Integration: guides/integration-overview/data-integration.md
98     - Site Integration: guides/integration-overview/site-integration.md
```
**Result:** Parser error, see below:
```
[E 170914 11:13:18 ioloop:638] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "c:\python36\lib\site-packages\tornado\ioloop.py", line 1026, in _run
        return self.callback()
      File "c:\python36\lib\site-packages\livereload\handlers.py", line 67, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "c:\python36\lib\site-packages\livereload\watcher.py", line 73, in examine
        func and func()
      File "c:\python36\lib\site-packages\mkdocs\commands\serve.py", line 101, in builder 
        theme_dir=theme_dir
      File "c:\python36\lib\site-packages\mkdocs\config\base.py", line 177, in load_config
        cfg.load_file(config_file)
      File "c:\python36\lib\site-packages\mkdocs\config\base.py", line 123, in load_file
        return self.load_dict(utils.yaml_load(config_file))
      File "c:\python36\lib\site-packages\mkdocs\utils\__init__.py", line 71, in yaml_load
        return yaml.load(source, Loader)
      File "c:\python36\lib\site-packages\yaml\__init__.py", line 72, in load
        return loader.get_single_data()
      File "c:\python36\lib\site-packages\yaml\constructor.py", line 35, in get_single_data
        node = self.get_single_node()
      File "c:\python36\lib\site-packages\yaml\composer.py", line 36, in get_single_node
        document = self.compose_document()
      File "c:\python36\lib\site-packages\yaml\composer.py", line 55, in compose_document
        node = self.compose_node(None, None)
      File "c:\python36\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\python36\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "c:\python36\lib\site-packages\yaml\composer.py", line 82, in compose_node
        node = self.compose_sequence_node(anchor)
      File "c:\python36\lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
        node.value.append(self.compose_node(node, index))
      File "c:\python36\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\python36\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "c:\python36\lib\site-packages\yaml\composer.py", line 82, in compose_node
        node = self.compose_sequence_node(anchor)
      File "c:\python36\lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
        node.value.append(self.compose_node(node, index))
      File "c:\python36\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\python36\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
        while not self.check_event(MappingEndEvent):
      File "c:\python36\lib\site-packages\yaml\parser.py", line 98, in check_event
        self.current_event = self.state()
      File "c:\python36\lib\site-packages\yaml\parser.py", line 439, in parse_block_mapping_key
        "expected <block end>, but found %r" % token.id, token.start_mark)
    yaml.parser.ParserError: while parsing a block mapping
      in "C:\MkDocsSite\mkdocs.yml", line 93, column 9
    expected <block end>, but found '-'
      in "C:\MkDocsSite\mkdocs.yml", line 94, column 9
```

### Package versions

* Python: `3.6.1`
* MkDocs: `0.16.3`
* Material: `1.10.0`

### Project configuration

``` yaml
extra:
      feature:
      tabs: true
...
markdown_extensions:
  - codehilite(linenums=false)
  - admonition
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.escapeall
  - footnotes

#Before modifying
- Home: index.md
- Guides: 
  - Overview: guides/index.md
  - Integration Overview: 
    - Introduction: guides/integration-overview/index.md
    - Data Integration: guides/integration-overview/data-integration.md
    - Site Integration: guides/integration-overview/site-integration.md
  - Application Setup:
    - Introduction: guides/applications/index.md
    - Admin Application: guides/applications/admin.md
    - Integration Application: guides/applications/integration.md
...
```

### System information

* OS: Windows 10 Pro v1703
* Browser: Chrome Version 61.0.3163.79 64-bit)

**Comment by squidfunk** [comment]
This is a long standing MkDocs issue and has nothing to do with Material in the first place, see: https://github.com/mkdocs/mkdocs/issues/73 and https://github.com/mkdocs/mkdocs/pull/1042

**Comment by martinbira** [comment]
Indeed it seems to be! Didn't see it in the mkdocs issues, thanks!

**Comment by squidfunk** [comment]
Closing this for the reasons stated above.
