### ISSUE TITLE
TypeError: Object of type Undefined is not JSON serializable

### ISSUE THREAD

**Issue by pawamoy** [squidfunk/mkdocs-material#4946]
### Context

Just trying to build mkdocstrings' docs :slightly_smiling_face: 
Happens with mkdocs-material 9.0.7 and 9.0.8, not 9.0.6.

### Bug description

```console
$ mkdocs build
  INFO     -  Cleaning site directory
  INFO     -  Building documentation to directory: /media/data/dev/mkdocstrings/site
  INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
    - reference/autorefs/plugin.md
    - reference/autorefs/references.md
  Traceback (most recent call last):
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/bin/mkdocs", line 8, in <module>
      sys.exit(cli())
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/mkdocs/__main__.py", line 250, in build_command
      build.build(cfg, dirty=not clean)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/mkdocs/commands/build.py", line 320, in build
      _build_theme_template(template, env, files, config, nav)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/mkdocs/commands/build.py", line 118, in _build_theme_template
      output = _build_template(template_name, template, files, config, nav)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/mkdocs/commands/build.py", line 97, in _build_template
      output = template.render(context)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/jinja2/environment.py", line 1301, in render
      self.environment.handle_exception()
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/jinja2/environment.py", line 936, in handle_exception
      raise rewrite_traceback_stack(source=source)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/material/404.html", line 4, in top-level template code
      {% extends "main.html" %}
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/material/main.html", line 4, in top-level template code
      {% extends "base.html" %}
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/material/base.html", line 148, in top-level template code
      {% block site_nav %}
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/material/base.html", line 156, in block 'site_nav'
      {% include "partials/nav.html" %}
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/material/partials/nav.html", line 27, in top-level template code
      {% include "partials/nav-item.html" %}
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/material/partials/nav-item.html", line 91, in top-level template code
      {{ render(nav_item, path, level) }}
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/jinja2/runtime.py", line 777, in _invoke
      rv = self._func(*arguments)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/material/partials/nav-item.html", line 48, in template
      <nav class="md-nav" data-md-level="{{ level }}" aria-labelledby="{{ path }}_label" aria-expanded="{{ nav_item.active | tojson }}">
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/jinja2/filters.py", line 1688, in do_tojson
      return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
    File "/media/data/dev/mkdocstrings/__pypackages__/3.10/lib/jinja2/utils.py", line 658, in htmlsafe_json_dumps
      dumps(obj, **kwargs)
    File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.10.8/lib/python3.10/json/__init__.py", line 238, in dumps
      **kw).encode(obj)
    File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.10.8/lib/python3.10/json/encoder.py", line 199, in encode
      chunks = self.iterencode(o, _one_shot=True)
    File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.10.8/lib/python3.10/json/encoder.py", line 257, in iterencode
      return _iterencode(o, 0)
    File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.10.8/lib/python3.10/json/encoder.py", line 179, in default
      raise TypeError(f'Object of type {o.__class__.__name__} '
  TypeError: Object of type Undefined is not JSON serializable
```

### Related links

Reported here https://github.com/mkdocstrings/mkdocstrings/issues/528

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10530597/example.zip)

### Steps to reproduce

```bash
git clone git@github.com:mkdocstrings/mkdocstrings
cd mkdocstrings
python3 -m venv venv
source venv/bin/activate
pip install pdm
pdm install -G docs
mkdocs build
```

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. I'm stunned. When can `nav_item.active` be undefined? Is this the result of some plugin?

**Comment by squidfunk** [comment]
Hmm, so this is not a minimal reproduction. In fact, the `mkdocs.yml` is 100 lines long, there are 8 plugins configured and a lot of files in `docs` + I can't get it to run since there are too many dependencies. Please reduce the example to the bare minimum that showcases the error. Otherwise I'm unable to look into it 🙁

**Comment by pawamoy** [comment]
Oh, looks like it was coming from mkdocs-section-index: https://github.com/oprypin/mkdocs-section-index/releases/tag/v0.3.5. Updated the plugin locally and it works again. Closing!

**Comment by squidfunk** [comment]
Okay, great!

**Comment by glasgowm148** [comment]
Same issue for me, would be good to add this to the build update instructions to check plugins.
