### ISSUE TITLE
mkdocs gh-deploy fails in docker image

### ISSUE THREAD

**Issue by mvertes** [squidfunk/mkdocs-material#510]
## Description

This bug relates to the docker image rather than mkdocs-material itself.
The gh-deploy command fails due to lack of git and openssh in the image. 

### Expected behavior
```
$ docker run --rm -ti -v `pwd`:/docs squidfunk/mkdocs-material gh-deploy
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /docs/site 
INFO    -  Copying '/docs/site' to 'gh-pages' branch and pushing to GitHub. 
INFO    -  Your documentation should shortly be available at: https://....
```

### Actual behavior
```
$ docker run --rm -ti -v `pwd`:/docs squidfunk/mkdocs-material gh-deploy
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /docs/site 
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 11, in <module> load_entry_point('mkdocs==0.16.3', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__ return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mkdocs-0.16.3-py2.7.egg/mkdocs/__main__.py", line 213, in gh_deploy_command gh_deploy.gh_deploy(cfg, message=message, force=force)
  File "/usr/lib/python2.7/site-packages/mkdocs-0.16.3-py2.7.egg/mkdocs/commands/gh_deploy.py", line 54, in gh_deploy if not _is_cwd_git_repo():
  File "/usr/lib/python2.7/site-packages/mkdocs-0.16.3-py2.7.egg/mkdocs/commands/gh_deploy.py", line 16, in _is_cwd_git_repo stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child raise child_exception
OSError: [Errno 2] No such file or directory
```

### Workaround

Run the docker in default mode: 

```
docker run --rm  --name mkdocs -ti -v $HOME/.ssh:/root/.ssh -v $PWD:/docs squidfunk/mkdocs-material
```

Execute a shell into it, add `git` and `openssh` fixes the problem

```
docker exec -ti mkdocs sh
/docs # apk add -U git openssh
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
(1/9) Installing libssh2 (1.8.0-r1)
(2/9) Installing libcurl (7.56.0-r0)
(3/9) Installing pcre (8.41-r0)
(4/9) Installing git (2.13.5-r0)
(5/9) Installing openssh-keygen (7.5_p1-r1)
(6/9) Installing openssh-client (7.5_p1-r1)
(7/9) Installing openssh-sftp-server (7.5_p1-r1)
(8/9) Installing openssh-server (7.5_p1-r1)
(9/9) Installing openssh (7.5_p1-r1)
Executing busybox-1.26.2-r4.trigger
OK: 79 MiB in 34 packages
/docs # mkdocs gh-deploy
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /docs/site 
INFO    -  Copying '/docs/site' to 'gh-pages' branch and pushing to GitHub. 
INFO    -  Your documentation should shortly be available at: https://...
```

Note: I bind ~/.ssh volume to provide private ssh key for github, could be avoided perhaps by using https clone instead

**Comment by squidfunk** [comment]
Works for me with:

``` sh
docker run --rm -it -v ~/.ssh:/root/.ssh -v `pwd`:/docs squidfunk/mkdocs-material gh-deploy
```
