### ISSUE TITLE
 Error: Unrecognised theme 'material'

### ISSUE THREAD

**Issue by ksingh7** [squidfunk/mkdocs-material#52]
Guys i am trying to use this great looking material theme. As mentioned in instructions i did installation and setup like this.
- `pip install mkdocs-material`
- Added `theme: 'material'` in `mkdocs.yml`
- Restarted `mkdocs serve` 

Browser did'nt got updated with material theme, instead i am getting this in mkdocs serve logs. Can you please help

```
INFO    -  Building documentation...
ERROR   -  Config value: 'theme'. Error: Unrecognised theme 'material'. The available installed themesare:
[E 161010 01:48:04 ioloop:633] Exception in callback <bound method type.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 1041, in _run
        return self.callback()
      File "/usr/local/lib/python2.7/site-packages/livereload/handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/usr/local/lib/python2.7/site-packages/livereload/watcher.py", line 73, in examine
        func and func()
      File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 71, in builder
        theme=theme,
      File "/usr/local/lib/python2.7/site-packages/mkdocs/config/base.py", line 164, in load_config
        "Aborted with {0} Configuration Errors!".format(len(errors))
    ConfigurationError: Aborted with 1 Configuration Errors!
```

**Comment by ksingh7** [comment]
Hi @squidfunk looking for pointers on this.

**Comment by urosjarc** [comment]
I think that you install material for python3.

**Comment by squidfunk** [comment]
Please provide some more details on

- Python version
- MkDocs version
- Material version

so I can reproduce this error.

**Comment by urosjarc** [comment]
@ksingh7 if you installed py3 pip is pointing on python3. Try this...

```
pip2 install ...
```

**Comment by ksingh7** [comment]
@squidfunk  @urosjarc 

Here are more details, will really appreciate your help to get this working
```
karasing-OSX:~$ pip list | grep -i material
mkdocs-material (0.2.4)
karasing-OSX:~$
karasing-OSX:~$ python --version
Python 2.7.11
karasing-OSX:~$ mkdocs --version
mkdocs, version 0.15.3
karasing-OSX:~$
```

**Comment by squidfunk** [comment]
Versions look good to me. I have actually no explanation because I cannot reproduce this error. Can you post on the mkdocs issue tracker? The material theme isn't found, so since you're the only one with this problem of which I know it may be a problem with mkdocs.

**Comment by squidfunk** [comment]
Closing issue due to inactivity.

**Comment by g0dlight** [comment]
I'm getting the same error

**Comment by JerryC8080** [comment]
@ksingh7  @g0dlight 

Your are suggested to make `mkdocs` and `meterial` on the save way.     
Such as both installed by `pip`.

I meet the same problem when I installed mkdocs by `brew install mkdocs` and meterial by `pip install mkdocs-meterial`.

We can see the differ of variable `theme_dir` that mkdocs on different way installed.

On My Device:    
**On `brew install mkdocs`**
```
$ mkdocs -v build
......
DEBUG   -  Config value: 'theme_dir' = ['/usr/local/Cellar/mkdocs/0.16.1_1/libexec/lib/python2.7/site-packages/mkdocs/themes/mkdocs', u'/usr/local/Cellar/mkdocs/0.16.1_1/libexec/lib/python2.7/site-packages/mkdocs/assets/search']
...
```

**On `pip install mkdocs`** 
```
$ mkdocs -v build
...
DEBUG   -  Config value: 'theme_dir' = ['/usr/local/lib/python2.7/site-packages/mkdocs/themes/mkdocs', u'/usr/local/lib/python2.7/site-packages/mkdocs/assets/search']
...
```

**And `pip install mkdocs-meterial`**
```
$ pip install mkdocs-material

Requirement already satisfied: mkdocs-material in /usr/local/lib/python2.7/site-packages
```

So, Make `mkdocs` and `themes` install in the save directory.
Because `mkdocs build` and `mkdocs serve` command will load the same level directory to find theme.

Hope the way i solve my problem will be same on you.

**Comment by robmerki** [comment]
**SOLVED!**

@JerryC8080 thank you so much for your help.

I had at some point installed mkdocs via Homebrew and later switched to the pip install. Somewhere my config paths had become mixed up.

Solution:
```
$ brew uninstall --force mkdocs
```
```
$ pip uninstall mkdocs
```
```
$ pip install mkdocs
```

**Comment by welkie** [comment]
It's probably worth documenting this issue in the documentation. I ran into it too, because I installed mkdocs using apt-get but then had to use pip anyways to install the material theme. The mix caused the issue for me. I had to uninstall mkdocs in apt-get and install it again using pip.

**Comment by squidfunk** [comment]
Agreed, I will add a note on this. Nevertheless it's more related to MkDocs than to Material, but it doesn't hurt to point it out.

**Comment by squidfunk** [comment]
Added a new section called **Troubleshooting**:
http://squidfunk.github.io/mkdocs-material/getting-started/#troubleshooting

**Comment by welkie** [comment]
Awesome. :)

Great looking theme by the way. My documentation for a project just looked 100x better using this. xD

**Comment by josetomas** [comment]
Hi! 
I've been having the same problem. I uninstalled mkdocs from apt-get and installed directly from pip. 
But when I want to use mkdocs serve I receive the following error: 
bash: /usr/bin/mkdocs: No existe el archivo o el directorio (the file or directory doesn't exist).

**Comment by lopezunwired** [comment]
> **SOLVED!**
> 
> @JerryC8080 thank you so much for your help.
> 
> I had at some point installed mkdocs via Homebrew and later switched to the pip install. Somewhere my config paths had become mixed up.
> 
> Solution:
> 
> ```
> $ brew uninstall --force mkdocs
> ```
> 
> ```
> $ pip uninstall mkdocs
> ```
> 
> ```
> $ pip install mkdocs
> ```

This worked for me too! In fact, I don't recall installing mkdocs with homebrew, but when you use 'force' it seemed to clean it up. I also noticed now I have two paths for python to look in.

**Comment by RoseauHan** [comment]
> **SOLVED!**
> 
> @JerryC8080 thank you so much for your help.
> 
> I had at some point installed mkdocs via Homebrew and later switched to the pip install. Somewhere my config paths had become mixed up.
> 
> Solution:
> 
> ```
> $ brew uninstall --force mkdocs
> ```
> 
> ```
> $ pip uninstall mkdocs
> ```
> 
> ```
> $ pip install mkdocs
> ```

Work for me too! Thanks!

**Comment by barisalhan** [comment]
SOLVED!

In the mkdocs.yml file, you should change this line as follows:

theme:
  name: 'material'

to this version,

theme:
  name: 'mkdocs'

OR

theme:
  name: 'readthedocs'

**Comment by xvilo** [comment]
It's weird that this is still happening, just updated 'mkdocs' with brew and this happened. These paths should be fixed

**Comment by squidfunk** [comment]
Don't install `mkdocs` via Homebrew. See [the troubleshooting guide](https://squidfunk.github.io/mkdocs-material/getting-started/#troubleshooting)

**Comment by seekM** [comment]
I'm having this problem when using material via cloning from github. 

I'm using Windows 10 and installed `python` (and `pip`) from its [website](https://www.python.org/downloads/).
I installed `mkdocs` with `pip install mkdocs`.

My setup: 

```
PS C:\Users\User\Documents\music\project> python --version
Python 3.8.2
PS C:\Users\User\Documents\music\project> pip --version
pip 20.1 from c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip (python 3.8)
PS C:\Users\User\Documents\music\project> mkdocs --version
mkdocs, version 1.1 from c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\mkdocs (Python 3.8)
```

Then I'm doing `git clone https://github.com/squidfunk/mkdocs-material.git` from the same directory as described [here](https://squidfunk.github.io/mkdocs-material/getting-started/#with-git).


```
PS C:\Users\User\Documents\music\project> ls .\mkdocs-material\material\

    Verzeichnis: C:\Users\User\Documents\music\project\mkdocs-material\material

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10.05.2020     21:51                .icons
d-----       10.05.2020     21:51                assets
d-----       10.05.2020     21:51                overrides
d-----       10.05.2020     21:51                partials
-a----       10.05.2020     21:51            150 404.html
-a----       10.05.2020     21:51           8912 base.html
-a----       10.05.2020     21:51             88 main.html
-a----       10.05.2020     21:51           2492 mkdocs_theme.yml
-a----       10.05.2020     21:51              0 __init__.py
```
```
PS C:\Users\User\Documents\music\project> mkdocs serve
INFO    -  Building documentation...
ERROR   -  Config value: 'theme'. Error: Unrecognised theme name: 'mkdocs-material/material'. The available installed themes are: mkdocs, readthedocs

Aborted with 1 Configuration Errors!
``` 

My `mkdocs.yml`:
```
site_name: Test
nav:
    - Home: index.md
    
theme:
  name: mkdocs-material/material
```

Other themes, e.g. `readthedocs`, work fine. `material` also works finde when I insatall it via `pip`, but I don't want that because its latest release doesn't seem to include the [favicon bug fix](https://github.com/mkdocs/mkdocs/issues/1717#issuecomment-543307147) yet. Any idea?

**Comment by squidfunk** [comment]
It must be `custom_dir`, see:
https://squidfunk.github.io/mkdocs-material/getting-started/#configuration

**Comment by seekM** [comment]
Oops, thanks!

**Comment by Atlas-Night-Out** [comment]
> brew uninstall --force mkdocs

What paths are we suppose to use, its so frustrating and complaicated to know where the phython is installed and if you need to point to taht path or not? 

I have so many different version on one pc and added them all in the path, and MK docs works ok but struggling to move over to windows 11 and finding MK docs is not working but I dont think I have added a path yet!

So i have just done a download and installed python 3.12.3 now and its gone into C:\Program Files\Python312
so do i point to that folder?  

error I'm getting is ERROR   -  Config value 'theme': Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs

and

mkdocs serve
'mkdocs' is not recognized as an internal or external command,
operable program or batch file.

**Comment by squidfunk** [comment]
You just need to make sure that `mkdocs` and `mkdocs-material` are installed in same site packages folder, i.e., they use the exact same Python version. Unfortunately, I cannot assist with Windows-specific problems, as I'm not a Windows user

**Comment by SunDevil311** [comment]
> [@ksingh7](https://github.com/ksingh7) [@g0dlight](https://github.com/g0dlight)
> 
> Your are suggested to make `mkdocs` and `meterial` on the save way. Such as both installed by `pip`.
> 
> I meet the same problem when I installed mkdocs by `brew install mkdocs` and meterial by `pip install mkdocs-meterial`.
> 
> We can see the differ of variable `theme_dir` that mkdocs on different way installed.
> 
> On My Device: **On `brew install mkdocs`**
> 
> ```
> $ mkdocs -v build
> ......
> DEBUG   -  Config value: 'theme_dir' = ['/usr/local/Cellar/mkdocs/0.16.1_1/libexec/lib/python2.7/site-packages/mkdocs/themes/mkdocs', u'/usr/local/Cellar/mkdocs/0.16.1_1/libexec/lib/python2.7/site-packages/mkdocs/assets/search']
> ...
> ```
> 
> **On `pip install mkdocs`**
> 
> ```
> $ mkdocs -v build
> ...
> DEBUG   -  Config value: 'theme_dir' = ['/usr/local/lib/python2.7/site-packages/mkdocs/themes/mkdocs', u'/usr/local/lib/python2.7/site-packages/mkdocs/assets/search']
> ...
> ```
> 
> **And `pip install mkdocs-meterial`**
> 
> ```
> $ pip install mkdocs-material
> 
> Requirement already satisfied: mkdocs-material in /usr/local/lib/python2.7/site-packages
> ```
> 
> So, Make `mkdocs` and `themes` install in the save directory. Because `mkdocs build` and `mkdocs serve` command will load the same level directory to find theme.
> 
> Hope the way i solve my problem will be same on you.

I have a slightly different setup, as I'm using mkdocs and mkdocs-material on Windows, both installed via pip. Though they were both installed with pip, I was getting the same error reported in this thread.

However, running `mkdocs -v build` somehow added the material theme to my configuration, whereas it wasn't showing up prior. I have no idea what it actually does (it said "Documentation Built," but it appears to have created/copied quite a few files), but it works.

Not sure if I missed this in the setup instructions, but I don't recall seeing anything of the sort. Just wanted to let you know that it worked for me!
