### ISSUE TITLE
social plugin is prone to get broken with KeyError: 'Regular'

### ISSUE THREAD

**Issue by ssbarnea** [squidfunk/mkdocs-material#5201]
### Context

While writing documentation in liv emode with `mkdocs server`, I observed that very easily I get the social plugin cache broken badly, in a way that only `rm -rf .cache/plugin` would fix it.

### Bug description

```
INFO     -  [16:30:11] Detected file changes
INFO     -  Building documentation...
Traceback (most recent call last):
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 116, in serve
    server.serve()
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/mkdocs/livereload/__init__.py", line 162, in serve
    self._build_loop()
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/mkdocs/livereload/__init__.py", line 184, in _build_loop
    func()
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/mkdocs/commands/build.py", line 332, in build
    config.plugins.run_event('post_build', config=config)
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/mkdocs/plugins.py", line 522, in run_event
    result = method(**kwargs)
             ^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 173, in on_post_build
    promise.result()
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 180, in _cache_image
    image = render_function()
            ^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 160, in <lambda>
    render_function = lambda: self._render_card(site_name, title, description)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 200, in _render_card
    font = self._get_font("Bold", 36)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 188, in _get_font
    return ImageFont.truetype(self.font[kind], size)
                              ~~~~~~~~~^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11.2/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 409, in <lambda>
    return defaultdict(lambda: font["Regular"], font)
                               ~~~~^^^^^^^^^^^
KeyError: 'Regular'
```

### Related links

Luckly, I was able to spot the workaround with google, as someone included it in their documentation: https://github.com/konveyor/pelorus/blob/master/docs/Development.md?plain=1#L608-L612

### Reproduction

In order to find the root cause of the problem, I would also include the cache content, especially as I am using custom fonts.

```
$ tree .cache
.cache
└── plugin
    └── social
        ├── 3c06449231a35cd3ac363f41cbb3e836.png
        ├── RedHatDisplay-Italic-VariableFont_wght.ttf
        ├── RedHatDisplay-VariableFont_wght.ttf
        ├── a8da5a4236fba836c87990a46ff46317.png
        ├── aa4b7476d651d50782820e729d482336.png
        ├── b114ab71a8d0917db42b504599f32d0f.png
        ├── c2ab2285cb928f8e72cd96f207ecebf5.png
        ├── d15096398591a12c52b410120956076d.png
        ├── ed9e7dd89266cd6c98d894b606f08351.png
        ├── fa0e0d13d851b07de2264f1c5fe79c94.png
        └── static
            ├── RedHatDisplay-Black.ttf
            ├── RedHatDisplay-BlackItalic.ttf
            ├── RedHatDisplay-Bold.ttf
            ├── RedHatDisplay-BoldItalic.ttf
            ├── RedHatDisplay-ExtraBold.ttf
            ├── RedHatDisplay-ExtraBoldItalic.ttf
            ├── RedHatDisplay-Italic.ttf
            ├── RedHatDisplay-Light.ttf
            ├── RedHatDisplay-LightItalic.ttf
            ├── RedHatDisplay-Medium.ttf
            ├── RedHatDisplay-MediumItalic.ttf
            ├── RedHatDisplay-Regular.ttf
            ├── RedHatDisplay-SemiBold.ttf
            └── RedHatDisplay-SemiBoldItalic.ttf
```

I suspect that this bug might happen only to those using custom fonts. My mkdocs-ansible theme is based on material and only includes few settings that we wanted to make consistent, no real custom code. That being the custom font configuration https://github.com/ansible/mkdocs-ansible/blob/main/src/mkdocs_ansible/mkdocs_theme.yml#L21-L26

### Steps to reproduce

Not established yet but for sure there is something inside this `.cache` that is causing the issue.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting – unfortunately, we can't help you debug your packaged custom theme. Could you please try to reproduce this with a stock `material` configuration and include a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#minimal-reproduction)? Note that it is mandatory to create the reproduction with the [`info` plugin](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file). Without something that we can run, it's hard to find and fix the issue. 

Happy to look into then. Thank you.

**Comment by squidfunk** [comment]
Closing as not reproducible. We're happy to reopen and investigate once we get what we requested in https://github.com/squidfunk/mkdocs-material/issues/5201#issuecomment-1470613313.

**Comment by ssbarnea** [comment]
To be honest, I am inclined to believe that the bug is not caused by material at all, likely a caching bug in mkdocs itself. Still, due to its random nature, I was not able to reproduce it. Still, I found occurence of it online, so is not unique to me. I might try to chase the guy that documented the workaround in the first place, maybe we can narrow it down.

**Comment by rktic** [comment]
FYI: I had the same issue. Deleting the cache folder solved it.

**Comment by squidfunk** [comment]
Thanks! We'll look into improving cache invalidation in the near future 😊

**Comment by rktic** [comment]
For the record:
I don't consider myself being your targeted user group (UX-designer, avoiding anything git-related, almost inexistent Linux experience). Given the amount of dependencies et al, I managed to make this work anyway.

What I'm trying to say is: this works very well already :)
