### ISSUE TITLE
mkdocs exit with a python stack error when using pymdownx plugins on CentOS 7

### ISSUE THREAD

**Issue by kayari75** [squidfunk/mkdocs-material#535]
## Description

On a CentOS 7, when I add a pymdownx plugins in the markdown_extensions section in mkdocs.yml, I get an error when a build with mkdocs.

mkdocs build or serve exit with a python stack error.

### Expected behavior

I expect to use pymdownx plugins.

### Actual behavior
```
$ mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/XXXX/Documents/winbind/site 
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 11, in <module>
    load_entry_point('mkdocs==0.16.3', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 380, in build
    build_pages(config, dirty=dirty)
  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 333, in build_pages
    dump_json)
  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 189, in _build_page
    site_navigation=site_navigation
  File "/usr/lib/python2.7/site-packages/mkdocs/commands/build.py", line 59, in convert_markdown
    extension_configs=config['mdx_configs']
  File "/usr/lib/python2.7/site-packages/mkdocs/utils/__init__.py", line 364, in convert_markdown
    extension_configs=extension_configs or {}
  File "/usr/lib/python2.7/site-packages/markdown/__init__.py", line 137, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/lib/python2.7/site-packages/markdown/__init__.py", line 165, in registerExtensions
    ext.extendMarkdown(self, globals())
  File "/usr/lib/python2.7/site-packages/pymdownx/arithmatex.py", line 195, in extendMarkdown
    config = self.getConfigs()
  File "/usr/lib/python2.7/site-packages/markdown/extensions/__init__.py", line 28, in getConfigs
    return dict([(key, self.getConfig(key)) for key in self.config.keys()])
AttributeError: 'list' object has no attribute 'keys'
```

### Steps to reproduce the bug

1. Add a pymdownx plugin in markdown_extensions.
2. build or serve : mkdocs build

### Package versions

* Python: 2.7.5
* MkDocs: 0.16.3
* Material: 1.12.1

### Project configuration

``` yaml
---
site_name: My doc
theme: material
extra:
  logo:
    icon: 'device_hub'
  language: 'en'
    
markdown_extensions:
  - pymdownx.arithmatex
  - markdown_include.include
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - tables
...
```

### System information

* OS: CentOS 7.4
* Browser: Chrome 59.0.3071.115

**Comment by facelessuser** [comment]
1. @squidfunk  does not directly support `pymdownx.arithmatex`, but I do.  Stuff like this might be more appropriate filed over there.
2. I'm not sure what version of pymdown-extensions you are using.
3. I use the latest Material and the latest pymdownx-extensions to generate my docs, and pymdownx-extensions is specifically using `pymdownx.arithmatex`: https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml#L85.  See document: http://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#examples.

I do not think you are having a linux specific issue as I deploy my docs from Linux.

One thing to note, you are specifying the default extensions incorrectly, they should be specified as `markdown.extensions.tables` instead of just `tables`.  I believe you've specified `pymdownx.arithmatex` correctly though.  You could try specifying extensions with no config with a `:` at the end, but I don't think that is your problem.  It may help to post your whole config and specify the version of pymdown-extensions.

**Comment by squidfunk** [comment]
Closing this, because as @facelessuser said, this is certainly an error with an upstream project, not with Material itself.
