### ISSUE TITLE
TypeError: unhashable type: 'ExtraScriptValue'

### ISSUE THREAD

**Issue by LaoMa1961** [squidfunk/mkdocs-material#5793]
### Context

I am try to "serve" a mkdocs document folder but after to have uploaded all the latest editions of everything it needs, I get an error and I am not able to understand where to fix it, even if I have surfed on internet about it....

### Bug description

This is the console report at the command "mkdocs serve"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\serve.py", line 98, in serve
    builder(config)
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\serve.py", line 79, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\build.py", line 340, in build
    _build_theme_template(template, env, files, config, nav)
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\build.py", line 110, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\build.py", line 87, in _build_template
    context = config.plugins.on_template_context(context, template_name=name, config=config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\plugins.py", line 555, in on_template_context
    return self.run_event(
           ^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs_print_site_plugin\plugin.py", line 288, in on_template_context
    self.context['extra_javascript'] = [get_relative_url(f, self.print_page.file.url) for f in config.get('extra_javascript')]
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs_print_site_plugin\plugin.py", line 288, in <listcomp>
    self.context['extra_javascript'] = [get_relative_url(f, self.print_page.file.url) for f in config.get('extra_javascript')]
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbonelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\utils\__init__.py", line 243, in get_relative_url
    dest_parts = _norm_parts(url)
                 ^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'ExtraScriptValue'
### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[SPINLevel_doc.zip](https://github.com/squidfunk/mkdocs-material/files/12229314/SPINLevel_doc.zip)

### Steps to reproduce

Just "mkdocs serve"

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by LaoMa1961** [comment]
I have discovered that it is related to the plugin print-site. I have installed following the instruction at 
[Documentation mkdocs-print-site-plugin](https://timvink.github.io/mkdocs-print-site-plugin/print_page.html)
with the command 
_pip3 install mkdocs-print-site-plugin_

remarking the command _#- print-site_  will build the project (but no print possibility).

Thanks for help
Maurizio

**Comment by squidfunk** [comment]
Thanks for reporting. However, as you already noticed, this is an issue with the print-site plugin. Please report it to the authors of the plugin, as we can do nothing on our side. Thank you.
