### ISSUE TITLE
custom_dir: theme_overrides settings error in mkdocs.yml file

### ISSUE THREAD

**Issue by vishwanathan-m1** [squidfunk/mkdocs-material#5915]
### Bug description

Unable to run the commands: 'mkdocs serve' and 'mkdocs build' when using the custom_dir: theme_overrides settings error in mkdocs.yml file.

### Related links

1. https://squidfunk.github.io/mkdocs-material/customization/?h=theme+overrides#setup-and-theme-structure	

2. https://github.com/squidfunk/mkdocs-material/issues/3356
	

### Reproduction

Unable to run the commands: 'mkdocs serve' and 'mkdocs build' when using the custom_dir: theme_overrides settings error in mkdocs.yml file. Attached is the mkdocs_themes.zip file containing files: "mkdocs.yml"" and all files inside "theme_overrides" folder.  
[mkdocs_themes.zip](https://github.com/squidfunk/mkdocs-material/files/12461536/mkdocs_themes.zip)

### Steps to reproduce

1. Installed version of python: Python 3.11.5
2. Installed version of pip: pip 23.2.1 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)
3. Operating system details: 
		Os: macOS Monterey
		Version: 12.3
		Chip: Apple M1 Pro
4. Mkdocs Version: mkdocs, version 1.5.2 from /usr/local/lib/python3.11/site-packages/mkdocs (Python 3.11)
5. Mkdocs-Material Version:
	 Name: mkdocs-material
	 Version: 9.2.5
	 Summary: Documentation that simply works
	 Home-page: 
	 Author: 
	 Author-email: Martin Donath <martin.donath@squidfunk.com>
	 License: 
	 Location: /usr/local/lib/python3.11/site-packages
	 Requires: babel, colorama, jinja2, lxml, markdown, mkdocs, mkdocs-material-extensions, paginate, pygments, pymdown-extensions, readtime, regex, requests
	 Required-by:
6. Create a project folder: /Users/user/Desktop/volt-mx-doc-opnsrc, run the command : mkdocs new .
7. Add the settings in zip file as attached. 
8. Run the command mkdocs serve / mkdocs build without setting  custom_dir: theme_overrides in mkdocs.yml file - it works fine without any error.
9. Run the command mkdocs serve / mkdocs build with setting  custom_dir: theme_overrides in mkdocs.yml file - following error is displayed and site is not built.

	Traceback (most recent call last):
	File "/usr/local/bin/mkdocs", line 8, in <module>
	sys.exit(cli())
	^^^^^
	File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in call
	return self.main(*args, **kwargs)
	^^^^^^^^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
	rv = self.invoke(ctx)
	^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
	return _process_result(sub_ctx.command.invoke(sub_ctx))
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
	return ctx.invoke(self.callback, **ctx.params)
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
	return __callback(*args, **kwargs)
	^^^^^^^^^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/mkdocs/main.py", line 270, in serve_command
	serve.serve(**kwargs)
	File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
	builder(config)
	File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
	build(config, live_server=None if is_clean else server, dirty=is_dirty)
	File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 340, in build
	_build_theme_template(template, env, files, config, nav)
	File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 110, in _build_theme_template
	output = _build_template(template_name, template, files, config, nav)
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 89, in _build_template
	output = template.render(context)
	^^^^^^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
	self.environment.handle_exception()
	File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
	raise rewrite_traceback_stack(source=source)
	File "/usr/local/lib/python3.11/site-packages/material/404.html", line 4, in top-level template code
	{% extends "main.html" %}
	File "/Users/theme_overrides/main.html", line 2, in top-level template code
	{% extends "base.html" %}
	File "/usr/local/lib/python3.11/site-packages/material/base.html", line 157, in top-level template code
	{% block site_nav %}
	^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/material/base.html", line 165, in block 'site_nav'
	{% include "partials/nav.html" %}
	^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/material/partials/nav.html", line 4, in top-level template code
	{% import "partials/nav-item.html" as item with context %}
	^^^^^^^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1405, in make_module
	return TemplateModule(self, ctx)
	^^^^^^^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1535, in init
	body_stream = list(template.root_render_func(context)) # type: ignore
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	File "/Users/theme_overrides/partials/nav-item.html", line 154, in top-level template code
	navigation items #} {{ render(nav_item, path, level) }}
	^^^^^^^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
	rv = self._func(*arguments)
	^^^^^^^^^^^^^^^^^^^^^^
	File "/Users/theme_overrides/partials/nav-item.html", line 19, in template
	#} {% set class = "md-nav__item" %} {% if nav_item.active %} {% set class =
	^^^^^^^^^^^^^^^^^^^^^^^^^
	File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
	return getattr(obj, attribute)
	^^^^^^^^^^^^^^^^^^^^^^^
	jinja2.exceptions.UndefinedError: 'nav_item' is undefined.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This error is not related to Material for MkDocs, but to MkDocs in general. Please report it upstream. Additionally, the problem might be in your customizations or overrides.
