### ISSUE TITLE
Build failure with 9.4.3+insiders4.42.0

### ISSUE THREAD

**Issue by andrewfullard** [squidfunk/mkdocs-material#6137]
### Context

I am the maintainer for our documentation, using material-insiders.

### Bug description

Installed the latest insiders release along with the other requirements inside a conda env, in WSL2. The only conda command I used was `conda install pip`, then I ran `pip install .` inside the insiders repository.

Trying to build the docs produces the following traceback:

```
Traceback (most recent call last):
  File "/home/afullard/miniconda3/envs/build-docs/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/mkdocs/commands/build.py", line 340, in build
    _build_theme_template(template, env, files, config, nav)
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/mkdocs/commands/build.py", line 110, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/mkdocs/commands/build.py", line 89, in _build_template
    output = template.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/afullard/ICER/public-documentation/overrides/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/material/templates/base.html", line 64, in top-level template code
    {% block fonts %}
^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/material/templates/base.html", line 66, in block 'fonts'
    {% set text = config.theme.font.get("text", "Roboto") %}
^^^^^^^^^^^^^^^^^^^^^
  File "/home/afullard/miniconda3/envs/build-docs/lib/python3.11/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'get'
```

### Related links

I did not find related issues to this problem

### Reproduction

[9.4.3+insiders.4.42.0-jinja2-build-issue.zip](https://github.com/squidfunk/mkdocs-material/files/12818938/9.4.3%2Binsiders.4.42.0-jinja2-build-issue.zip)

### Steps to reproduce

1. Extract zip
2. Create conda env and activate
3. Install pip into conda env with `conda install pip`
4. Open the latest insiders repository and run `pip install .`
5. Try to build the docs with `mkdocs build` or `mkdocs serve`

Result of pip list:
```
Package                                   Version
----------------------------------------- ---------------------
Babel                                     2.13.0
certifi                                   2023.7.22
charset-normalizer                        3.3.0
click                                     8.1.7
colorama                                  0.4.6
ghp-import                                2.1.0
gitdb                                     4.0.10
GitPython                                 3.1.37
idna                                      3.4
Jinja2                                    3.0.3
Markdown                                  3.4.4
MarkupSafe                                2.1.3
mergedeep                                 1.3.4
mkdocs                                    1.5.3
mkdocs-git-authors-plugin                 0.7.2
mkdocs-git-revision-date-localized-plugin 1.2.0
mkdocs-material                           9.4.3+insiders.4.42.0
mkdocs-material-extensions                1.2
mkdocs-redirects                          1.2.1
packaging                                 23.2
paginate                                  0.5.6
pathspec                                  0.11.2
pip                                       23.2.1
platformdirs                              3.11.0
Pygments                                  2.16.1
pymdown-extensions                        10.3
python-dateutil                           2.8.2
pytz                                      2023.3.post1
PyYAML                                    6.0.1
pyyaml_env_tag                            0.1
regex                                     2023.10.3
requests                                  2.31.0
setuptools                                68.0.0
six                                       1.16.0
smmap                                     5.0.1
urllib3                                   2.0.6
watchdog                                  3.0.0
wheel                                     0.41.2
```

Result of conda list

```
# packages in environment at /home/afullard/miniconda3/envs/build-docs:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
babel                     2.13.0                   pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.08.22           h06a4308_0  
certifi                   2023.7.22                pypi_0    pypi
charset-normalizer        3.3.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
ghp-import                2.1.0                    pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.37                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
markdown                  3.4.4                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
mergedeep                 1.3.4                    pypi_0    pypi
mkdocs                    1.5.3                    pypi_0    pypi
mkdocs-git-authors-plugin 0.7.2                    pypi_0    pypi
mkdocs-git-revision-date-localized-plugin 1.2.0                    pypi_0    pypi
mkdocs-material           9.4.3+insiders.4.42.0          pypi_0    pypi
mkdocs-material-extensions 1.2                      pypi_0    pypi
mkdocs-redirects          1.2.1                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
openssl                   3.0.11               h7f8727e_2  
packaging                 23.2                     pypi_0    pypi
paginate                  0.5.6                    pypi_0    pypi
pathspec                  0.11.2                   pypi_0    pypi
pip                       23.2.1          py311h06a4308_0  
platformdirs              3.11.0                   pypi_0    pypi
pygments                  2.16.1                   pypi_0    pypi
pymdown-extensions        10.3                     pypi_0    pypi
python                    3.11.5               h955ad1f_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyyaml-env-tag            0.1                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
setuptools                68.0.0          py311h06a4308_0  
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   2.0.6                    pypi_0    pypi
watchdog                  3.0.0                    pypi_0    pypi
wheel                     0.41.2          py311h06a4308_0  
xz                        5.4.2                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0 
```

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting and providing the reproduction. Does it also happen when you install via `pip` [as recommended in our Insiders getting started guide](https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#with-pip)? I'm not a user of `conda` or WSL, but please try to install with `pip` only to see if the problem is triggered by a combination of `conda` and `pip`.

**Comment by squidfunk** [comment]
Wait, no, I think I know what the problem is. Your configuration is wrong:

__You have__

``` yaml
theme:
  name: material
  font: Gotham
```

__You need__

``` yaml
theme:
  name: material
  font:
    text: Gotham
```

[This is also explained in our documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#regular-font). I'm not sure why this ever worked for you, but it's clearly a configuration error. I recommend setting up [configuration validation](https://squidfunk.github.io/mkdocs-material/creating-your-site/#minimal-configuration-visual-studio-code) to catch such errors earlier in the process.

**Comment by andrewfullard** [comment]
Thank you for finding the error! That fixed it. We'll set up configuration validation right away.
