### ISSUE TITLE
Category and Archive Error

### ISSUE THREAD

**Issue by userofgithub023897** [squidfunk/mkdocs-material#6270]
### Context

If some use in Markdown sites in front matter more than 10 (estimation) times

- the same category
- the same MM/YYYY (e.g. 2022-12-16)

the server stops and throws an error.

### Bug description

```bash
mkdocs serve

...

ERROR   -  Error building page 'blog/archive/2022/12/page/2.md': Archive(title='Dezember 2022',
           url='/blog/archive/2022/12/') is not in list
Traceback (most recent call last):
  File "/opt/homebrew/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/commands/build.py", line 349, in build
    _build_page(
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/commands/build.py", line 222, in _build_page
    context = config.plugins.on_page_context(context, page=page, config=config, nav=nav)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/plugins.py", line 583, in on_page_context
    return self.run_event('page_context', context, page=page, config=config, nav=nav)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/material/plugins/blog/plugin.py", line 328, in on_page_context
    items[items.index(prev)] = page
          ^^^^^^^^^^^^^^^^^
ValueError: Archive(title='Dezember 2022', url='/blog/archive/2022/12/') is not in list
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- Installation via pip as recommended - [https://squidfunk.github.io/mkdocs-material/getting-started/#with-pip-latest](ttps://squidfunk.github.io/mkdocs-material/getting-started/#with-pip-latest)
- Updated to latest version [https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/)
- Built-in blog plugin: [https://squidfunk.github.io/mkdocs-material/plugins/blog/?h=archive#archive](https://squidfunk.github.io/mkdocs-material/plugins/blog/?h=archive#archive)

### Reproduction

[9.4.7-archive-category-bug.zip](https://github.com/squidfunk/mkdocs-material/files/13228297/9.4.7-archive-category-bug.zip)

### Steps to reproduce

If category and archive in the `mkdocs.yml` are set to `false` the `mkdocs serve` runs without any issue.

- categories: false
- archive: false

The tags plugin as reported in #5952 works fine. The same tag name can be used unlimited times in the Markdown files in front matter.

```bash
plugins:
  - blog:

...

      categories: false

...

      archive: false

```

### Browser

Chrome, Firefox, Other

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Indeed, there seems to be some issue with pagination. Temporary mitigation: Raise the number of items per page in pagination:

```
plugins:
  - blog:
      pagination_per_page: 1000
```
