### ISSUE TITLE
Can't set custom repo icon (and also custom logo in some cases)

### ISSUE THREAD

**Issue by nadimkobeissi** [squidfunk/mkdocs-material#6489]
### Bug description

Trying to set a custom repo icon [by following the Material for MkDocs docs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/) fails.

✅ This works (`mkdocs.yml`, icon placed in `docs/img/logo.svg`):
```yaml
theme:
  logo: img/logo.svg
```

❌ This **does not** work despite `mkdocs serve --strict` producing no errors and running the website (`mkdocs.yml`, icon placed in `docs/.icons/logo.svg`):
```yaml
theme:
  icon:
    logo: logo
```

❌ This **does not** work with `mkdocs serve` producing the following crash (`mkdocs.yml`, icon placed in `docs/.icons/logo.svg` and `docs/.icons/repo.svg`):
```yaml
theme:
  icon:
    logo: logo
    repo: repo
```

The crash:
```
nadim@Archangel ~/C/p/t/polygon-docs (nadim/fixes)> mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
Traceback (most recent call last):
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 340, in build
    _build_theme_template(template, env, files, config, nav)
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 110, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 89, in _build_template
    output = template.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/material/templates/404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/material/templates/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/material/templates/base.html", line 140, in top-level template code
    {% block header %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/material/templates/base.html", line 141, in block 'header'
    {% include "partials/header.html" %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/material/templates/partials/header.html", line 57, in top-level template code
    {% include "partials/source.html" %}
^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/material/templates/partials/source.html", line 7, in top-level template code
    {% include ".icons/" ~ icon ~ ".svg" %}
^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadim/Code/polygon/tkd/polygon-docs/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .icons/repo.svg
```

Note that the above crash is weird because both `logo.svg` and `repo.svg` are right there in `.icons`, and `logo.svg` is indeed found (despite not being applied to the site the same way it is in the first out of three configs listed above):

```
nadim@Archangel ~/C/p/t/polygon-docs (nadim/fixes) [1]> ls docs/.icons
Octal Permissions Size User  Date Modified Git Name
0644  .rw-r--r--   19k nadim 11 Dec 11:13   -N logo.svg
0755  .rwxr-xr-x  1.5k nadim 11 Dec 12:20   -N repo.svg
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Changing the logo and icons](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/)

### Reproduction

[9.5.1-cannot-change-icons.zip](https://github.com/squidfunk/mkdocs-material/files/13634941/9.5.1-cannot-change-icons.zip)

### Steps to reproduce

1. Run `mkdocs serve`
2. Can't find icons!

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. It appears you have not followed [our documentation on setting up custom icons](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons) – as [`custom_dir`](https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure) is not properly set up. Additionally, the `.icons` folder must not be located in the `docs` directory but in the `overrides` you specified when [extending the theme](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme), as documented.

Here's your example with the above corrections.

[9.5.1-cannot-change-icons.zip](https://github.com/squidfunk/mkdocs-material/files/13635174/9.5.1-cannot-change-icons.zip)

**Comment by nadimkobeissi** [comment]
@squidfunk Thanks for your patience and guidance, and apologies for wasting your time.

**Comment by nadimkobeissi** [comment]
@squidfunk Asking for this issue to be reopened, please: your suggested fix doesn't seem to work.

[9.5.1-custom-icons-still-dont-work.zip](https://github.com/squidfunk/mkdocs-material/files/13636161/9.5.1-custom-icons-still-dont-work.zip)

**Comment by alexvoss** [comment]
I have tried the `.zip` file @squidfunk sent back and it works for me. Tried the original `.zip` file and a) moved `.icons` out of `docs/` and into `override`, then declared `custom_dir: override` in `mkdocs.yml`. Seems to work fine for me. Unless there is some really weird interaction going on with the Windows Linux Subsystem, I'd say you must have missed something.

**Comment by squidfunk** [comment]
Just run the example I attached above. That's also why I shared:

1. The links to the documentation + the exact explanation what you have to do
2. A runnable example

**Comment by SilentGlasses** [comment]
Sorry to kick this off again, I did not want to start a new issue for one that already exists...   Just need some further explanation and make a suggestion. I may be understanding this wrong but.....

So as per this discussion. The instructions found at https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/ should not be followed?

The specific part about the Site Logo that is: 

**The logo can be changed to a user-provided image**

## Logo

The logo can be changed to a user-provided image (any type, incl. `*.png` and `*.svg`) located in the docs folder, or to any icon bundled with the theme. Add the following lines to `mkdocs.yml`:

```
theme:
  logo: assets/logo.png
```

What if I don't want to use it as an icon as the solution above suggests?

If using it as an icon is the only way to get a custom logo, then please update the instructions to reflect that. It's confusing to have instructions to use a custom logo that don't work.

I've tried it with both `docs/images/logo.png` and `docs/assets/logo.png`
