### ISSUE TITLE
Documentation for User Provided Logo not working

### ISSUE THREAD

**Issue by SilentGlasses** [squidfunk/mkdocs-material#6976]
### Description

Sorry to kick this off again, I did not want to start a new issue for one that already exists...   Just need some further explanation and make a suggestion. I may be understanding this wrong but.....

So as per this discussion in #6489. The instructions found at https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/ should not be followed?

The specific part about the Site Logo that is: 

**The logo can be changed to a user-provided image**

## Logo

The logo can be changed to a user-provided image (any type, incl. `*.png` and `*.svg`) located in the docs folder, or to any icon bundled with the theme. Add the following lines to `mkdocs.yml`:

```
theme:
  logo: assets/logo.png
```

What if I don't want to use it as an icon as the solution above suggests?

If using it as an icon is the only way to get a custom logo, then please update the instructions to reflect that. It's confusing to have instructions to use a custom logo that don't work.

I've tried it with both `docs/images/logo.png` and `docs/assets/logo.png` and I keep getting this error that makes it seem that it's looking for an icon...

```
Traceback (most recent call last):
  File "/home/username/Documents/dev/mydocs/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/mkdocs/commands/build.py", line 340, in build
    _build_theme_template(template, env, files, config, nav)
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/mkdocs/commands/build.py", line 110, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/mkdocs/commands/build.py", line 89, in _build_template
    output = template.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/material/templates/404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "/home/username/Documents/dev/mydocs/username.github.io/overrides/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/material/templates/base.html", line 140, in top-level template code
    {% block header %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/material/templates/base.html", line 141, in block 'header'
    {% include "partials/header.html" %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/material/templates/partials/header.html", line 13, in top-level template code
    {% include "partials/logo.html" %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/material/templates/partials/logo.html", line 8, in top-level template code
    {% include ".icons/" ~ icon ~ ".svg" %}
  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Documents/dev/mydocs/lib/python3.12/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .icons/assets/logo.png.svg
```

Also, it seems that only `.svg` images will work here as per the error above:

```
jinja2.exceptions.TemplateNotFound: .icons/assets/logo.png.svg
```

### Related links

- [Changing the logo and icons](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo)

### Proposed change

Remove options that don't function or should not be followed.

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by SilentGlasses** [comment]
Actually, closing this out. I realized my mistake...  
I had the logo settings sitting in the icon rather than it being it's own thing.
