### ISSUE TITLE
 Failed building wheel for tornado

### ISSUE THREAD

**Issue by CesMak** [squidfunk/mkdocs-material#775]
Hey there,

currently tried to install mkdocs-material in an anaconda environment. This worked usually but since today I got the following error:

 ```
pip install mkdocs-material --user
Requirement already satisfied: mkdocs-material in /home/mlampre/.local/lib/python2.7/site-packages (2.7.3)
Requirement already satisfied: pymdown-extensions>=4.10 in /home/mlampre/.local/lib/python2.7/site-packages (from mkdocs-material) (4.10.1)
Requirement already satisfied: tornado<5 in /usr/lib/python2.7/dist-packages (from mkdocs-material) (3.1.1)
Collecting Pygments>=2.2 (from mkdocs-material)
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Requirement already satisfied: mkdocs>=0.17.1 in /home/mlampre/.local/lib/python2.7/site-packages (from mkdocs-material) (0.17.3)
Collecting Markdown>=2.6.10 (from pymdown-extensions>=4.10->mkdocs-material)
  Using cached https://files.pythonhosted.org/packages/6d/7d/488b90f470b96531a3f5788cf12a93332f543dbab13c423a5e7ce96a0493/Markdown-2.6.11-py2.py3-none-any.whl
Requirement already satisfied: livereload>=2.5.1 in /home/mlampre/.local/lib/python2.7/site-packages (from mkdocs>=0.17.1->mkdocs-material) (2.5.2)
Requirement already satisfied: PyYAML>=3.10 in /usr/lib/python2.7/dist-packages (from mkdocs>=0.17.1->mkdocs-material) (3.10)
Requirement already satisfied: click>=3.3 in /home/mlampre/.local/lib/python2.7/site-packages (from mkdocs>=0.17.1->mkdocs-material) (6.7)
Requirement already satisfied: Jinja2>=2.7.1 in /usr/lib/python2.7/dist-packages (from mkdocs>=0.17.1->mkdocs-material) (2.7.2)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from livereload>=2.5.1->mkdocs>=0.17.1->mkdocs-material) (1.5.2)
Requirement already satisfied: markupsafe in /usr/lib/python2.7/dist-packages (from Jinja2>=2.7.1->mkdocs>=0.17.1->mkdocs-material) (0.18)
mkdocs 0.17.3 has requirement tornado<5.0,>=4.1, but you'll have tornado 3.1.1 which is incompatible.
Installing collected packages: Pygments, Markdown
Successfully installed Markdown-2.6.11 Pygments-2.2.0
```

Now if I install tornado I get this error:
```
  Failed building wheel for tornado
  Running setup.py clean for tornado
Failed to build tornado

```

BTW. I also get this error:

```
 pip install --upgrade tornado --user
Collecting tornado
  Using cached https://files.pythonhosted.org/packages/cf/d1/3be271ae5eba9fb59df63c9891fdc7d8044b999e8ac145994cdbfd2ae66a/tornado-5.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/usr/lib/python2.7/dist-packages/setuptools/extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 16, in <module>
        import pkg_resources
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-x5g88v2f/tornado/

```

Anyone here who knows how to solve this?

**Comment by squidfunk** [comment]
Any success?

**Comment by CesMak** [comment]
Hey :) 

- jap I somehow got it to work but I am not sure anymore what I did in detail.... 
- you can close this if you like
- However it had to do something with the new pip version 10 so I went back to 9 and I think that actually did the trick

**Comment by squidfunk** [comment]
Closing this, please re-open if it comes up again.
