### ISSUE TITLE
The social and rss plugins conflict

### ISSUE THREAD

**Issue by CLOVIS-AI** [squidfunk/mkdocs-material#7818]
### Context

I would like to use both the `social` and `rss` plugins together.

### Bug description

When using both `social` and `rss` together, the server crashes with:

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /assets/images/social/blog/posts/better-java-1.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x752087cb7ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

<details>
<summary>Full trace</summary>

Traceback (most recent call last):
2024-12-20T10:11:06.480536995Z   File "/usr/local/bin/mkdocs", line 8, in <module>
2024-12-20T10:11:06.480541955Z     sys.exit(cli())
2024-12-20T10:11:06.480546585Z              ^^^^^
2024-12-20T10:11:06.480551235Z   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
2024-12-20T10:11:06.480705515Z     return self.main(*args, **kwargs)
2024-12-20T10:11:06.480729815Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.480735755Z   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
2024-12-20T10:11:06.480899115Z     rv = self.invoke(ctx)
2024-12-20T10:11:06.480908075Z          ^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.480924515Z   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
2024-12-20T10:11:06.481189195Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-12-20T10:11:06.481199735Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.481204835Z   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2024-12-20T10:11:06.481414956Z     return ctx.invoke(self.callback, **ctx.params)
2024-12-20T10:11:06.481446256Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.481454266Z   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2024-12-20T10:11:06.481577126Z     return __callback(*args, **kwargs)
2024-12-20T10:11:06.481589366Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.481593926Z   File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 268, in serve_command
2024-12-20T10:11:06.481674776Z     serve.serve(**kwargs)
2024-12-20T10:11:06.481686756Z   File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 85, in serve
2024-12-20T10:11:06.481764926Z     builder(config)
2024-12-20T10:11:06.481774246Z   File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
2024-12-20T10:11:06.481819026Z     build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty)
2024-12-20T10:11:06.481832086Z   File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 310, in build
2024-12-20T10:11:06.481920186Z     _populate_page(file.page, config, files, dirty)
2024-12-20T10:11:06.481935526Z   File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 171, in _populate_page
2024-12-20T10:11:06.481992126Z     page.content = config.plugins.on_page_content(
2024-12-20T10:11:06.482000866Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.482005796Z   File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 638, in on_page_content
2024-12-20T10:11:06.482118596Z     return self.run_event('page_content', html, page=page, config=config, files=files)
2024-12-20T10:11:06.482141016Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.482150866Z   File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 566, in run_event
2024-12-20T10:11:06.482272707Z     result = method(item, **kwargs)
2024-12-20T10:11:06.482283407Z              ^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.482323457Z   File "/usr/local/lib/python3.11/site-packages/mkdocs_rss_plugin/plugin.py", line 293, in on_page_content
2024-12-20T10:11:06.482397927Z     image=self.util.get_image(
2024-12-20T10:11:06.482412127Z           ^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.482417767Z   File "/usr/local/lib/python3.11/site-packages/mkdocs_rss_plugin/util.py", line 566, in get_image
2024-12-20T10:11:06.482487317Z     img_length = self.get_remote_image_length(image_url=img_url)
2024-12-20T10:11:06.482518627Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.482526717Z   File "/usr/local/lib/python3.11/site-packages/mkdocs_rss_plugin/util.py", line 636, in get_remote_image_length
2024-12-20T10:11:06.482642967Z     req_response = self.req_session.request(
2024-12-20T10:11:06.482652837Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.482658117Z   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
2024-12-20T10:11:06.482761277Z     resp = self.send(prep, **send_kwargs)
2024-12-20T10:11:06.482808837Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.482814587Z   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
2024-12-20T10:11:06.482913547Z     r = adapter.send(request, **kwargs)
2024-12-20T10:11:06.482925097Z         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T10:11:06.482930137Z   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
2024-12-20T10:11:06.483067207Z     raise ConnectionError(e, request=request)
2024-12-20T10:11:06.483079517Z requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /assets/images/social/blog/posts/better-java-1.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x752087cb7ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))

</details>

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/tutorials/blogs/engage/#rss-feeds
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards

### Reproduction

Cannot generate it. Since the server crashes while starting, nothing is generated.

### Steps to reproduce

1. Clone `https://gitlab.com/clovis-ai/website.git`
2. Checkout commit `d60e8047c5e2c1ced650b10f7e753fc4a317936f`
3. Open `docs/website/mkdocs.yml`
4. Uncomment the `social` plugin
5. Run Material for MkDocs through the official Docker image

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is a problem of the RSS plugin, not the social plugin which [has been reported](https://github.com/Guts/mkdocs-rss-plugin/issues/257) and should be fixed in a newer version of the plugin. Please consult the documentation of the RSS plugin, or raise an issue upstream. Closing as out of scope.
