### ISSUE TITLE
How to customize favicon in template?

### ISSUE THREAD

**Issue by borekb** [squidfunk/mkdocs-material#789]
I'm trying to use favicon from a full URL, like this:

```
theme:
  favicon: https://mycdn.example/project/favicon.ico
```

This produces a markup like this:

```
<link rel="shortcut icon" href="./https://mycdn.example/project/favicon.ico">
```

So I'm trying to use [Overriding partials](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials) by putting `base.html` into my theme mod folder.

However, I'm not sure what to put there. [`src/base.html`](https://github.com/squidfunk/mkdocs-material/blob/416fd474b497c2f4b5307f75f3f6aed173179f16/src/base.html) cannot be used as is – I get an error like this:

```
INFO    -  Building documentation...
INFO    -  Cleaning site directory
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 11, in <module>
    load_entry_point('mkdocs==0.17.3', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mkdocs-0.17.3-py2.7.egg/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/usr/lib/python2.7/site-packages/mkdocs-0.17.3-py2.7.egg/mkdocs/commands/serve.py", line 117, in serve
    config = builder()
  File "/usr/lib/python2.7/site-packages/mkdocs-0.17.3-py2.7.egg/mkdocs/commands/serve.py", line 112, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/lib/python2.7/site-packages/mkdocs-0.17.3-py2.7.egg/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/usr/lib/python2.7/site-packages/mkdocs-0.17.3-py2.7.egg/mkdocs/commands/build.py", line 227, in build_pages
    build_error_template(template, env, config, site_navigation)
  File "/usr/lib/python2.7/site-packages/mkdocs-0.17.3-py2.7.egg/mkdocs/commands/build.py", line 115, in build_error_template
    build_template(template, env, config, site_navigation)
  File "/usr/lib/python2.7/site-packages/mkdocs-0.17.3-py2.7.egg/mkdocs/commands/build.py", line 88, in build_template
    output_content = template.render(context)
  File "/usr/lib/python2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/docs/theme-mods/base.html", line 329, in template
    {% if language in ($md-lunr-languages$) %}
jinja2.exceptions.TemplateSyntaxError: unexpected char u'$' at 11643
```

And [`material/base.html`](https://github.com/squidfunk/mkdocs-material/blob/416fd474b497c2f4b5307f75f3f6aed173179f16/material/base.html) contains specific versions etc.

Is there an easy way to customize the markup for favicon? Thanks.

**Comment by squidfunk** [comment]
The favicon is not expected to be hosted on a CDN. As this is a usecase that never came up until now, I would ask you to customize your template by overriding the `site_meta` block, so we don't make the logic too complicated, see:

https://github.com/squidfunk/mkdocs-material/blob/416fd474b497c2f4b5307f75f3f6aed173179f16/src/base.html#L34-L84

**Comment by borekb** [comment]
Great tip, thank you, exactly what I was looking for.
